### ISSUE TITLE
PipeWire crashes recording MIDI

### ISSUE THREAD

**Issue by user3354** [pipewire-debian/pipewire-debian#100]
Hi,

PipeWire 0.3.84 crashes very often when recording MIDI data. Tested with both Qtractor and Ardour. I will append some logs. Prior versions were OK, can someone confirm this behavior? How can I help debugging?

Arming tracks and MIDI data preview works, as soon as I start recording PipeWire crashes.

**Desktop (please complete the following information):**
 - Distro: Linux Mint 21.2
 - Desktop: Cinnamon
 - PipeWire Related packages Version: 0.3.84
 - Kernel version: 

=*Journal log and status of related services**
                                     
Nov 22 19:00:03 demo-desktop pipewire[15795]: spa.alsa: invalid sequence in buffer max:4096 offset:0 size:6184
Nov 22 19:00:54 demo-desktop pipewire[15795]: spa.alsa: invalid sequence in buffer max:4096 offset:0 size:6184
Nov 22 19:01:00 demo-desktop pipewire[15795]: spa.alsa: invalid sequence in buffer max:4096 offset:0 size:9232
Nov 22 19:01:57 demo-desktop pipewire[15795]: spa.alsa: front:2c: follower delay:1108 target:288 thr:256 resample:1, resync (0 suppressed)
Nov 22 19:02:31 demo-desktop kernel: [26326.791997] pipewire[15799]: segfault at 148 ip 00007fa9a6020650 sp 00007fa9a730fa00 error 4 in libspa-control.so[7fa9a6018000+a000]
Nov 22 19:02:31 demo-desktop systemd-coredump[28113]: Process 15795 (pipewire) of user 1000 dumped core.#012#012Found module linux-vdso.so.1 with build-id: 2b7896db2c90a504263aed9623f82485296ce9c0#012Found module libspa-control.so with build-id: 14976f2999cd625a53372c9b926e129bb0f043bc#012Found module libspa-audiomixer.so with build-id: ce12c2b6ac378727479306528d45669b21d5c82c#012Found module libspa-audioconvert.so with build-id: d29969254c3427db6026c36b8e206bfbe48fe24c#012Found module libmd.so.0 with build-id: cd2d2f71b3967ebde30e2aa43b8eb63339020c06#012Found module libbsd.so.0 with build-id: 9a6c72469251e2feb63e175ef5cb944ce6e00df3#012Found module libXdmcp.so.6 with build-id: 6b60f99504aa1d3999ea02a14366d1a39d6c5dcf#012Found module libXau.so.6 with build-id: 7089b383cacbfc1760634a3be19a923e51fe3315#012Found module libogg.so.0 with build-id: 842412496daf280ca5491dfb6581df5a378b72f0#012Found module libopus.so.0 with build-id: 75fc9fc43cb921c19173e69dbd720b905e6c2e2e#012Found module libvorbisenc.so.2 with build-id: 5d30e2a713669895dcf3b298ffed2e4ce56121e8#012Found module libvorbis.so.0 with build-id: fc9c832676aac541183d1b4774746bec48b66051#012Found module libFLAC.so.8 with build-id: 280eaf0c50a65ab561e803707fca2ec714cd28a3#012Found module libapparmor.so.1 with build-id: eedc16f04efd1e261091fea5c5306a57d7647d9f#012Found module libasyncns.so.0 with build-id: f192c4e5be41e201707cb7a5a962d43de3c675d2#012Found module libxcb.so.1 with build-id: 1bef862a339557aa16c34c7a4b27f8f3aea90517#012Found module libX11.so.6 with build-id: 37a5d7bbb78e3a99ea8376a7c80ea0c62fe06494#012Found module libX11-xcb.so.1 with build-id: 70f2a36d79c623f42fd70fa7ffb06d8877c74f16#012Found module libsndfile.so.1 with build-id: 08e2d078caf371d274047899e3526f7e6c0cf611#012Found module libpulsecommon-15.99.so with build-id: 1b08226b05ce048ed0fe3891ef46541035535196#012Found module libpulse.so.0 with build-id: 71fae00e01a094ea686803e24fbb20a895e77adf#012Found module libudev.so.1 with build-id: 08d71dea68e28c937d19b45ac924ef40c6c2e9f4#012Found module libasound.so.2 with build-id: d1986cd985564afaa9aa64c753423b01dd5b228e#012Found module libspa-alsa.so with build-id: c833cde310ab39e1938c9cb939ebf2eaf70e0946#012Found module libpipewire-module-session-manager.so with build-id: e807305a58350d5d81f0a39fe48ea7b44a988904#012Found module libpipewire-module-link-factory.so with build-id: 993a967ad2ce3c648e141b029b3813c3816068dd#012Found module libpipewire-module-adapter.so with build-id: 2495dd5480de974ea534f86fb9a328cd03f9172d#012Found module libpcre.so.3 with build-id: 3982f316c887e3ad9598015fa5bae8557320476a#012Found module libglib-2.0.so.0 with build-id: c74e800dfd5f72649d673b44292f4a817e45150b#012Found module libpipewire-module-access.so with build-id: a77ffb8d69bc62ba5407d6e3df639421d30fa47b#012Found module libpipewire-module-portal.so with build-id: b948350eaac21c9be5b2cd08eb597b68e832bfba#012Found module libpipewire-module-client-device.so with build-id: 3bd5cbf6a2fd4adbaf5740ab731612010f355425#012Found module libpipewire-module-client-node.so with build-id: 47c0df2bbac982529233b24f50e34c030acdb4b2#012Found module libpipewire-module-spa-node-factory.so with build-id: e59f247037729eb6ebe7637e28c98912b0e0b675#012Found module libpipewire-module-spa-device-factory.so with build-id: 242b5792abe8871e741363173e8b182b62d5c46b#012Found module libpipewire-module-metadata.so with build-id: d50dcb667eb6efa4ed9127fa0bb560e75a75a880#012Found module libpipewire-module-profiler.so with build-id: 8f283c7e03a70d8d918cce09aa261473e29ff474#012Found module libpcre2-8.so.0 with build-id: 184a841c55fb7fe5e3873fcda8368c71016cd54c#012Found module libselinux.so.1 with build-id: 6fa53202ce676297de24873c886443b2759bfd8a#012Found module libpipewire-module-protocol-native.so with build-id: 1be6252e4d7204bfc9027e489bb56e4f25dfe60a#012Found module libpipewire-module-rt.so with build-id: b261184a4cafe50f5fe0c74e728e7242f112200a#012Found module libdbus-1.so.3 with build-id: 63e8b99215502138cb63afd6d65851a5e837ed49#012Found module libspa-dbus.so with build-id: e8c3dc434f21b34b90ec40ada25dfdbd85f71943#012Found module libgpg-error.so.0 with build-id: 3fbec71c67bee60d8aef00697ee187079b0fb307#012Found module libgcrypt.so.20 with build-id: 60a5e524de0ed8323edf33e9eb9127a9eee02359#012Found module libcap.so.2 with build-id: b4bf900abf14aabe12d90988ceb30888acb2bcb0#012Found module liblz4.so.1 with build-id: a85971851cd059f1af80d553c8e7170d42ec59a1#012Found module libzstd.so.1 with build-id: 5d9d0d946a3154a748e87e17af9d14764519237b#012Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265#012Found module libsystemd.so.0 with build-id: e7268ae5d5222eb3c780756d071132ac49467d0b#012Found module libspa-journal.so with build-id: ab9def1f5942e9aefc80105270773c7fee866512#012Found module libm.so.6 with build-id: d2c7d1fdefc7a876b6017c090ccd55fb21e8d77f#012Found module libspa-support.so with build-id: c5d1c56921ac79e632b4306cbaca6cf3921813ad#012Found module ld-linux-x86-64.so.2 with build-id: 9718d3757f00d2366056830aae09698dbd35e32c#012Found module libc.so.6 with build-id: a43bfc8428df6623cd498c9c0caeb91aec9be4f9#012Found module libpipewire-0.3.so.0 with build-id: 260c501ba7dc8380f0fb0bf73d31f6c31610e67f#012Found module pipewire with build-id: 523831ba8ef2e93b67ef54485089f13b7c5c2930#012Stack trace of thread 15799:#012#0  0x00007fa9a6020650 n/a (libspa-control.so + 0x9650)#012#1  0x00007fa9a8bca14b n/a (libpipewire-0.3.so.0 + 0x6214b)#012#2  0x00007fa9a8c53aee n/a (libspa-support.so + 0x8aee)#012#3  0x00007fa9a8bac3fc n/a (libpipewire-0.3.so.0 + 0x443fc)#012#4  0x00007fa9a89d4ac3 start_thread (libc.so.6 + 0x94ac3)#012#5  0x00007fa9a8a66a40 __clone3 (libc.so.6 + 0x126a40)#012#012Stack trace of thread 15795:#012#0  0x00007fa9a8a6601e epoll_wait (libc.so.6 + 0x12601e)#012#1  0x00007fa9a8c61618 n/a (libspa-support.so + 0x16618)#012#2  0x00007fa9a8c53a2d n/a (libspa-support.so + 0x8a2d)#012#3  0x00007fa9a8bcabf4 pw_main_loop_run (libpipewire-0.3.so.0 + 0x62bf4)#012#4  0x000055b7649975db n/a (pipewire + 0x15db)#012#5  0x00007fa9a8969d90 __libc_start_call_main (libc.so.6 + 0x29d90)#012#6  0x00007fa9a8969e40 __libc_start_main_impl (libc.so.6 + 0x29e40)#012#7  0x000055b764997775 n/a (pipewire + 0x1775)
.

**Comment by souravdas142** [comment]
@user3354   Can you please check its distro specific or need to report @upstream

**Comment by user3354** [comment]
This problem did not occur with later versions, this bug can be closed.

**Comment by souravdas142** [comment]
Closed as completed
