### ISSUE TITLE
wireplumber 0.5.1 / pipewire 1.0.5

### ISSUE THREAD

**Issue by the-nic** [pipewire-debian/pipewire-debian#103]
I know you're busy but, I just wanted to ping and ask if it was possible to update pipewire / wireplumber to the recent versions. Especially wireplumber has very useful fixes for bluetooth profile switching.

Thanks!

**Comment by souravdas142** [comment]
Yes I will do this weekend.

**Comment by rw-bowman** [comment]
If it isnt too much trouble could you enable for kubuntu/ubuntu 24.04?

**Comment by souravdas142** [comment]
@the-nic  Done. Please sync

**Comment by nemoforum** [comment]
@souravdas142 ,
Not pushing, just curious about Pipewire 1.2x and libcamera 0.3.x. I'm interested in this because Linux 6.10 includes an Intel IPU6 Driver for modern web cameras and libcamera 0.3.x is needed.
Thank you for your work!
