### ISSUE TITLE
Ubuntu 24

### ISSUE THREAD

**Issue by rw-bowman** [pipewire-debian/pipewire-debian#104]

**Comment by rw-bowman** [comment]
If possible could you enable this for kubuntu 24.04

**Comment by souravdas142** [comment]
@rw-bowman  Done. Please sync and try to upgrade.

**Comment by rw-bowman** [comment]
There seems to be an issue with the upgrade :dpkg: error processing archive /tmp/apt-dpkg-install-rvjBkQ/07-pipewire-bin_1.0.7-1~ubuntu24.04_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man7/libpipewire-module-access.7.gz', which is also in package libpipewire-0.3-modules:amd64 1.0.5-1

**Comment by souravdas142** [comment]
try sudo apt-get -o Dpkg::Options::="--force-overwrite" install <pkgName>

**Comment by rw-bowman** [comment]
--fix-broken-install seemed to fix it

**Comment by mxa** [comment]
neither `apt-get -o Dpkg::Options::="--force-overwrite" install ` nor `apt --fix-broken install` was able to fix the issue 
```
dpkg: error processing archive /var/cache/apt/archives/pipewire-bin_1.0.7-1~ubuntu24.04_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man7/libpipewire-module-access.7.gz', which is also in package libpipewire-0.3-modules:amd64 1.0.5-1
Errors were encountered while processing:
 /var/cache/apt/archives/pipewire-bin_1.0.7-1~ubuntu24.04_amd64.deb
```

**Comment by souravdas142** [comment]
Please upgrade 1.0.7-3 is released with fixes

**Comment by KaMyKaSii** [comment]
Here the update fails with the same error for version 1.0.7-3, even running the two proposed commands. But merging the two commands worked: `sudo apt-get -o Dpkg::Options::="--force-overwrite" --fix-broken install`
