### ISSUE TITLE
pipewire-pulse configuration files seem to be missing

### ISSUE THREAD

**Issue by mcarans** [pipewire-debian/pipewire-debian#11]
**If you Completed all troubleshoot options, check below**     
- [ x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [ x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
pipewire-pusle configuration files seem to be missing

**To Reproduce**
```
sudo apt install libfdk-aac2 libldacbt-{abr,enc}2 libopenaptx0
sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,bin,locales,tests}}
sudo apt install pipewire-doc 
sudo cp /usr/share/doc/pipewire/examples/systemd/user/pipewire-pulse.* /etc/systemd/user/
```

**Expected behavior**
Should copy files

**Screenshots**
```
cp: cannot stat '/usr/share/doc/pipewire/examples/systemd/user/pipewire-pulse.*': No such file or directory
> ls /usr/share/doc/pipewire/examples/
alsa.conf.d  ld.so.conf.d  README.audio

```
**Desktop (please complete the following information):**
 - Distro: [e.g. Ubuntu] Mint
 - Desktop Environment [e.g. Gnome] Cinnamon
 - Version [e.g. 20.04] 20.1

**Comment by pipewire-debian** [comment]
from where you got those information? why you need to copy those files? what is written over [debian pipewire wiki](https://wiki.debian.org/PipeWire) is deprecated for this repo. Did you read all instructions from the [Project wiki](../wiki/Home) ? @mcarans this repo follows a straight forward way to install and woks out of the box.

**Comment by mcarans** [comment]
Thanks for the clarification and for the work on this. It is working for me now. Closing.
