### ISSUE TITLE
Upgrade problem with 0.3.29

### ISSUE THREAD

**Issue by mcarans** [pipewire-debian/pipewire-debian#16]
**If you Completed all troubleshoot options, check below**     
- [X]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [X]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
After upgrading to 0.3.29, the sound settings were gone. I got the error: Unit file pipewire-pulse.socket does not exist

**To Reproduce**
From 0.3.28 upgrade to 0.3.29.

**Expected behavior**
0.3.29 installs and works

**Desktop (please complete the following information):**
 - Distro: [e.g. Ubuntu] Mint
 - Desktop Environment [e.g. Gnome] Cinnamon
 - Version [e.g. 20.04] 20.1

**Resolution**
Uninstalling and reinstalling Pipewire worked ie.
```
sudo apt remove gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,media-session,bin,locales,tests}}
sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,media-session,bin,locales,tests}}
```
Then follow instructions for installation from there.

Although I have resolved the problem, I am reporting it in case it helps others with the same problem and in case there is a fix that you can make.

**Comment by souravdas142** [comment]
Sorry man, This is effect of believing `debian` packaging blindly. They never do anything correctly, This repo again rebase on  their repo, As some package splitted from other package, the prolem came. 
The issue can be resolved making `pipewire-media-session` dependency of `pipewire-pulse` and `pipewire-pulse` itself dependencies of `pipewire-bin`

**Comment by souravdas142** [comment]
All problem should solves with 1c0e643851f36533b0c152a9c093bb563829e598 wait for rebuild by launchpad.

**Comment by souravdas142** [comment]
@mcarans  with publishing [`pipewire-0.3.29-2`](https://launchpad.net/~pipewire-debian/+archive/ubuntu/pipewire-upstream/+sourcepub/12476175/+listing-archive-extra) All problems should sorted out. Please upgrade. while upgrading, If packages are `kept back` upgrade with `--with-new-pkgs` this is default behaviour if a package changes its dependencies

**Comment by mcarans** [comment]
@souravdas142 Worked for me thx!

**Comment by souravdas142** [comment]
should i leave it opened for others or close it? @mcarans

**Comment by mcarans** [comment]
I guess people won't have this problem now so OK to close. I leave it up to you @souravdas142.

**Comment by pipewire-debian** [comment]
Ok closing for now, If needed, will be opened again.
