### ISSUE TITLE
Issue with instructions

### ISSUE THREAD

**Issue by mcarans** [pipewire-debian/pipewire-debian#21]
I tried uninstalling and reinstalling the latest version. I got error:
`libspa-0.2-jack : Depends: video-dsp-play but it is not installable`
`pipewire-tests : Depends: video-dsp-play but it is not installable`

The instructions need to change to:
`sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,modules} pipewire{,-{audio-client-libraries,pulse,media-session,bin,locales}}`

**Comment by souravdas142** [comment]
Sorry fix is up :sweat_smile: meanwhile you are struggling. please update and upgrade about 30 mins later.

**Comment by souravdas142** [comment]
The problem was in  `shlibs.local` https://github.com/pipewire-debian/pipewire-debian/blob/329aef14bc35a1a587b4206957089b62ee1bc021/pipewire/debian/shlibs.local#L2

removed this line, and it should fix the problem. The fix is up

**Comment by mcarans** [comment]
@souravdas142  Will that also fix:
`pipewire-tests : Depends: video-dsp-play but it is not installable` ?

**Comment by souravdas142** [comment]
yes

**Comment by mcarans** [comment]
Uninstall and reinstall of new version worked. Closing.
