### ISSUE TITLE
No audio output device in Microsoft Teams for Linux, Skype (with solution)

### ISSUE THREAD

**Issue by avoidik** [pipewire-debian/pipewire-debian#23]
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
After PipeWire installation there is no output devices in Microsoft Teams desktop for Linux application available.

**To Reproduce**
In Microsoft Teams settings it's impossible to set audio output device, the list is empty.

**Expected behavior**
Select audio output device in Microsoft Teams settings

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Distro: Ubuntu/Mint
 - Desktop Environment: Mate
 - Version: 20.04

**Journal log and status of related services**

Solution - https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/838

**Comment by souravdas142** [comment]
@avoidik  devs are asking for feedback if `master` did  fix for the issue, are you asking to build from master ? I do not do that. This repo mean to release on every upstream release and not from `master`. However If you want to test and want to reply back to the devs I can help then by building from master and publish it to [`testing`](https://launchpad.net/~pipewire-debian/+archive/ubuntu/bionic-qt5125) branch. 

I've not this problem, See               
         
![image](https://user-images.githubusercontent.com/24272753/124432872-b9ab3880-dd8f-11eb-9baf-36c443a3fc4d.png)

It seems whoever have SOF, Can reproduce the problem, see https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/838#note_874817

**Comment by souravdas142** [comment]
@avoidik  did v0.3.32 solved the problem ?

**Comment by souravdas142** [comment]
someone reported there, the problem is solved now.
