### ISSUE TITLE
Make a notice that this might cause broken dependencies

### ISSUE THREAD

**Issue by jacksongoode** [pipewire-debian/pipewire-debian#24]
I've had a few instances where this upstream will cause some weird dependency problems. For example, installing steam.

**Comment by souravdas142** [comment]
I need more details, to solve dependencies problem.

**Comment by souravdas142** [comment]
@jacksongoode   I need more details, to solve dependencies problem. is it the same problem : https://bugs.launchpad.net/ubuntu/+source/pipewire/+bug/1931312 ? OP also post a solution there, you can check.

**Comment by jacksongoode** [comment]
This is my bad I thought that there was some build tool dependency from the Pipewire PPA that was running amok! I'll close this.
