### ISSUE TITLE
Can't start pipewire-pulse.socket.

### ISSUE THREAD

**Issue by knaiunsoo** [pipewire-debian/pipewire-debian#25]
**If you Completed all troubleshoot options, check below**     
- [y]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [y]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
Can't start `pipewire-pulse.socket` (and make sound server work....sad

**To Reproduce**
Just followed the step-by-step guide,then it can't working anyway,so I edited the `pipewire-pulse.service`and removed `Requires=pipewire-pulse.socket,Also=pipewire-pulse.socket`,now I can start `pipewire-pulse.service`alone and`pactl info`has message!But the book still haven't any sound and the setting page always grey...plz help me get it done(even can't back to `pulseaudio` lol.

**Expected behavior**

**Screenshots**
`pactl info`
![选区_410](https://user-images.githubusercontent.com/83066800/126142398-6ef7485f-2605-455d-85a0-ada9b54d5ae6.png)
`systemctl --user --now status`
![选区_409](https://user-images.githubusercontent.com/83066800/126136639-e9bf0f5d-ccf5-4f2a-ad1d-7c7a483f40f4.png)
`没有那个文件或目录` means `that file or dir not exist` (sorry I tried to set `LANG=en_US` but it have some strange char...

**Desktop (please complete the following information):**
 - Distro: [Pop!os]
 - Desktop Environment [Gnome 3.38.3]
 - Version [20.10]

**Journal log and status of related services**
~~History overriding~~

**Comment by souravdas142** [comment]
@knaiunsoo  I think this issue should move to [upstream issue](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues). please recreate one with details.

**Comment by souravdas142** [comment]
@knaiunsoo  any news with v0.3.32 ?
