### ISSUE TITLE
Sink is not being detected on system start up

### ISSUE THREAD

**Issue by luni3359** [pipewire-debian/pipewire-debian#29]
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
The package itself works perfectly fine, however one of the recent updates has caused pipewire to fail to connect the audio sink, but the source works perfectly, however this can be fixed by simply restarting the pipewire services as noted on the wiki, but it has to be done every system restart.

**To Reproduce**
I'm not sure, it randomly started happening after an update (and I'm not sure which).

**Expected behavior**
When the system starts, pipewire should detect my headset speakers as a sink without a service restart. The source microphone is already detected without issues.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Distro: KDE Neon User Edition 5.22 x86_64
 - KDE Plasma 5.22.4

**Journal log and status of related services**
Here's a gist of `systemctl status --user pipewire*`
https://gist.github.com/luni3359/1144047c6f38299a307a1328a5d197fe

Please let me know if this is too little information to work with, this is all I could come up with to troubleshoot my issue.

**Comment by souravdas142** [comment]
This is not a packaging issue. In that case I cant help you. Can you please report the same on upstream ? you can create an issue to upstream from https://gitlab.freedesktop.org/pipewire/pipewire/-/issues . Thanks.

**Comment by luni3359** [comment]
Thanks for your help!

**Comment by luni3359** [comment]
For future reference, it seems like the exact same problem has already been reported.
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1478
