### ISSUE TITLE
💥💥 Github wiki Released 💥💥 Please Contribute to wiki and this Project 💥💥

### ISSUE THREAD

**Issue by pipewire-debian** [pipewire-debian/pipewire-debian#3]
💥💥 **[Wiki](https://github.com/pipewire-debian/pipewire-debian/wiki) for this repo has been added**💥💥

<br />
:writing_hand: &nbsp; <b>PLEASE CONTRIBUTE TO THIS WIKI AND PROJECT</b> 

----

:warning: &nbsp;&nbsp;**IF THIS REPO IS NOT UPDATED FOR MORE THAN 30 DAYS IN A ROW, PLEASE FORK AND MAINTAIN YOUR OWN**       
&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **THIS WIKI DESCRIBES EVERYTHING YOU NEED TO KNOW TO BUILD A PACKAGE FOR DEBIAN BASED DISTROS...**     
&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **PLEASE TRY TO KEEP THIS PROJECT ALIVE**

**Comment by souravdas142** [comment]
No need to show this under issue more
