### ISSUE TITLE
Repo error

### ISSUE THREAD

**Issue by jabbermacy** [pipewire-debian/pipewire-debian#30]
hello, getting this error up update, can you help? ignoring repo security isn't working
https://imgur.com/XYvGWCv.png

**Comment by souravdas142** [comment]
edit  `/etc/apt/sources.list.d/pipewire-upstream.list` and replace `bullseye` with `hirsute` and then do a `sudo apt-get update`

**Comment by jabbermacy** [comment]
thanks, it's close, but I did not manually hold back pipewire, I DID hold wine-staging, I did global unhold, did not work
https://imgur.com/TMZgGFI.png

**Comment by souravdas142** [comment]
does it solve with `sudo apt-get full-upgrade` ? It just upgrade pipewire and leave wine untouched as its held.

**Comment by jabbermacy** [comment]
it's still held, no clue how/why, it's not locked in synaptic, not held,  this is CB++ on deb11 BTW  https://imgur.com/f5aTU65.png

**Comment by jabbermacy** [comment]
here's full term https://imgur.com/wmIeA9D

**Comment by souravdas142** [comment]
does it effect with `sudo apt-get -f install` and `sudo apt-get install pipewire=0.3.34-2~ubuntu21.04` ? give full terminal output.

**Comment by jabbermacy** [comment]
https://imgur.com/VyDrk1d
it still thinks PW is held, no clue why, I globally UNHELD all

**Comment by souravdas142** [comment]
> https://imgur.com/VyDrk1d
> it still thinks PW is held, no clue why, I globally UNHELD all


ok... we are too close... try to install `libpipewire-0.3-modules=0.3.34-2~ubuntu21.04` and give screenshot.

**Comment by jabbermacy** [comment]
i tried to get libc6 but version is <2.33, I don't know how to resolve, I'm sorry I'm no idiot but not linux genius either :-)
https://i.imgur.com/ZAhwG79.png

**Comment by souravdas142** [comment]
Ah my bad...!! I did not realise bullseye in the same timeline as ubuntu's focal (20.04) not hirsute.

https://github.com/pipewire-debian/pipewire-debian/issues/30#issuecomment-907616290  look at the comment, It would be `focal` in place of `hirsute`. and then do a `sudo apt update && sudo apt upgrade`. After this definitely all problems are sorted out.

**Comment by souravdas142** [comment]
did you solve the problem ? @jabbermacy

**Comment by souravdas142** [comment]
Closing since OP didn't reply back for a long time.
