### ISSUE TITLE
bluetoothd[1001]: a2dp-sink profile connect failed for xx:yy:xx:yy:xx:yy: Protocol not available

### ISSUE THREAD

**Issue by Crandel** [pipewire-debian/pipewire-debian#34]
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
I'm trying to connect my earphones (Mifo O5 plus, AAC codec) vie Bluetooth and I always got Failed error message. Pairing was successfull. The same earphones connect perfectly from arch host.

**Desktop (please complete the following information):**
 - Distro: Ubuntu
 - Desktop Environment: Swaywm compiled from master branch
 - Version: 20.04

**Journal log and status of related services**
bluetoothd[1001]: a2dp-sink profile connect failed for xx:yy:xx:yy:xx:yy: Protocol not available

**bluez-monitor.conf**

``` conf
# Bluez monitor config file for PipeWire version "0.3.30" #
#
# Copy and edit this file in /etc/pipewire/media-session.d/
# for systemwide changes or in
# ~/.config/pipewire/media-session.d/ for local changes.

properties = {
    # Enable mSBC support, disabled by default. Be aware that
    # mSBC is not expected to work on all headset + adapter combinations.
    # This can be overloaded for a specific device and native backend
    # in rules section.
    bluez5.msbc-support   = true

    bluez5.sbc-xq-support = true

    # Enabled headset roles (default: [ hsp_hs hfp_ag ]), this
    # property only applies to native backend. Currently some headsets
    # (Sony WH-1000XM3) are not working with both hsp_ag and hfp_ag
    # enabled, disable either hsp_ag or hfp_ag to work around it.
    #
    # Supported headset roles: hsp_hs (HSP Headset),
    #                          hsp_ag (HSP Audio Gateway),
    #                          hfp_hf (HFP Hands-Free),
    #                          hfp_ag (HFP Audio Gateway)
    bluez5.headset-roles = [ hsp_hs hsp_ag hfp_ag hfp_hf ]

    # Enabled A2DP codecs (default: all).
    bluez5.codecs = [ aac aptx aptx_hd sbc ]

    # Properties for the A2DP codec configuration
    bluez5.default.rate     = 48000
    bluez5.default.channels = 2
}

rules = [
    # An array of matches/actions to evaluate.
    {
        # Rules for matching a device or node. It is an array of
        # properties that all need to match the regexp. If any of the
        # matches work, the actions are executed for the object.
        matches = [
            {
                # This matches all cards.
                device.name = "~bluez_card.*"
            }
        ]
        actions = {
            # Actions can update properties on the matched object.
            update-props = {

                # Auto-connect device profiles on start up or when only partial
                # profiles have connected. Disabled by default if the property
                # is not specified.
                #bluez5.auto-connect = [
                #    hfp_hf
                #    hsp_hs
                #    a2dp_sink
                #    hfp_ag
                #    hsp_ag
                #    a2dp_source
                #]
                bluez5.auto-connect  = [ a2dp_sink a2dp_source hfp_hf hsp_hs ]

                # Overload mSBC support for native backend and a specific device.
                bluez5.msbc-support = true

                # Hardware volume control (default: [ hfp_ag hsp_ag a2dp_source ])
                bluez5.hw-volume = [
                    hfp_hf
                    hsp_hs
                    hfp_ag
                    hsp_ag
                    a2dp_source
                ]

                # LDAC encoding quality
                # Available values: auto (Adaptive Bitrate, default)
                #                   hq   (High Quality, 990/909kbps)
                #                   sq   (Standard Quality, 660/606kbps)
                #                   mq   (Mobile use Quality, 330/303kbps)
                bluez5.a2dp.ldac.quality  = auto

                # AAC variable bitrate mode
                # Available values: 0 (cbr, default), 1-5 (quality level)
                bluez5.a2dp.aac.bitratemode = 5

                # Profile connected first
                # Available values: a2dp-sink (default), headset-head-unit
                device.profile = a2dp-sink
            }
        }
    }
    {
        matches = [
            {
                # Matches all sources.
                node.name = "~bluez_input.*"
            }
            {
                # Matches all sinks.
                node.name = "~bluez_output.*"
            }
        ]
        actions = {
            update-props = {
                #node.nick            = "My Node"
                #node.nick            = null
                #priority.driver      = 100
                #priority.session     = 100
                node.pause-on-idle    = false
                #resample.quality     = 4
                #channelmix.normalize = false
                #channelmix.mix-lfe   = false
                session.suspend-timeout-seconds = 0      # 0 disables suspend
                #monitor.channel-volumes = false

                # A2DP source role, "input" or "playback"
                # Defaults to "playback", playing stream to speakers
                # Set to "input" to use as an input for apps
                bluez5.a2dp-source-role = playback
            }
        }
    }
]
```

**Comment by souravdas142** [comment]
hii... Thanks for the reporting... 

> \# Bluez monitor config file for PipeWire version "0.3.30" #

Are you sure the config is from v0.3.37 ?  copy all configs from `/usr/share/pipewire` to `/etc/` or `~/.config/` **or** remove configs from both location If you not want to  modify any configs.

**Comment by Crandel** [comment]
I removed all files from `~/.config/pipewire` (no folder `/etc/pipewire`), copy only `with-pulseaudio` to `~/.config/pipewire/media-session.d` directory. Tried to restart {pipewire,pipewire-pulse}.service. Result the same. Even after reboot

**Comment by souravdas142** [comment]
Well, I've just pushed 0.3.38 please install and test. 
What you need to do : 
1. delete all configs from `/etc/pipewire` and `~/.config/pipewire` 
2. disable all pipewire services : `systemctl --user --now disable pipewire{,-pulse}.{socket,service} pipewire-media-session.service`
3. re enable them : `systemctl --user --now enable pipewire{,-pulse}.{socket,service} pipewire-media-session.service`

Its enough i think to fix your problem.

**Comment by souravdas142** [comment]
Or does removing `pulseaudio-module-bluetooth` fix the problem ?? **please try https://github.com/pipewire-debian/pipewire-debian/issues/34#issuecomment-931379681 before removing this package.**

**Comment by Crandel** [comment]
I have no `pulseaudio-module-bluetooth` package installed
```
systemsctl status bluetooth.service
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-09-30 17:20:14 CEST; 2min 20s ago
       Docs: man:bluetoothd(8)
   Main PID: 1207 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 18688)
     Memory: 2.4M
     CGroup: /system.slice/bluetooth.service
             └─1207 /usr/lib/bluetooth/bluetoothd

Sep 30 17:20:14 user systemd[1]: Starting Bluetooth service...
Sep 30 17:20:14 user bluetoothd[1207]: Bluetooth daemon 5.53
Sep 30 17:20:14 user systemd[1]: Started Bluetooth service.
Sep 30 17:20:14 user bluetoothd[1207]: Starting SDP server
Sep 30 17:20:14 user bluetoothd[1207]: Bluetooth management interface 1.19 initialized
Sep 30 17:22:07 user bluetoothd[1207]: a2dp-sink profile connect failed for B0:06:32:79:B7:CA: Protocol not available
```

**Comment by souravdas142** [comment]
upload the `file`, `pw-dump > file` btw did you try https://github.com/pipewire-debian/pipewire-debian/issues/34#issuecomment-931379681 ?

**Comment by Crandel** [comment]
@souravdas142 Yes, just forgot to mention it

**Comment by Crandel** [comment]
[pw-dump.log](https://github.com/pipewire-debian/pipewire-debian/files/7260788/pw-dump.log)

**Comment by souravdas142** [comment]
Don't know... strange problem... did you properly stopped pulseaudio ? Is it possible for you to remove pulseaudio completely and then check ? 
`swaywm` generally not used with ubuntu. look its totally my PoV. ubuntu wayland is too old. may be there is some regression and already there is a fix for it in newer version. Can you switch to a Desktop (gnom wayland/xorg) ? and test ? From here I can't reproduce anything.

**Comment by Crandel** [comment]
I use ubuntu server edition, to have only necessary  packages. And I compile sway and all dependencies from latest source files. It was worked fine on this laptop on Arch linux, but for security reason I was forced to install Ubuntu on my working laptop. I you have no idea how to fix it, then just leave it, as it's definetly  not a bug in pipewire

**Comment by souravdas142** [comment]
> as it's definetly not a bug in pipewire

agreed

> all dependencies from latest source files

It also be possibility as you build everything from the source tree and the current pipewire binary is built  against the default source from ubuntu there may be a version mismatch ?? Can you try build the pipewire from master and just do a `make run` from the build env ??

**Comment by Crandel** [comment]
I don't think pipewire depends on sway at all. Everything works great, except bluetooth, so I thing maybe this is the problem in bluez version

**Comment by StyXman** [comment]
I have the same issue. All I can say is that if I disable `pipewire` and enable `pulseaudio`, it just works. Any ideas how else this can be debugged?

**Comment by souravdas142** [comment]
> I have the same issue. All I can say is that if I disable `pipewire` and enable `pulseaudio`, it just works. Any ideas how else this can be debugged?

please give more details ? pipewire version ? system details ? steps for reproduce ?

**Comment by StyXman** [comment]
Sorry for the delay, I was sick all week.

In fact, I just noticed this might be the wrong place (I'm using [k]ubuntu, not Debian, not at least on this machine where I see the problem).

`pipewire:amd64                                       0.3.48-1ubuntu1`

```
              *-usb:1
                   description: Bluetooth wireless interface
                   product: Bluetooth wireless interface
                   vendor: Intel Corp.
```

`Bus 001 Device 003: ID 8087:0a2b Intel Corp. Bluetooth wireless interface`

I just try to connect to the BT device (a BT headset) and I can see that message in the journal.

Let me know if you need more info.
