### ISSUE TITLE
Cannot find dependencies

### ISSUE THREAD

**Issue by JonLevin25** [pipewire-debian/pipewire-debian#35]
**If you Completed all troubleshoot options, check below**     
- [X]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [X]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
Tried to install on Raspberry Pi OS Buster using the gpg instrucitons.
Repository added OK, but `sudo apt update` ([log](https://github.com/pipewire-debian/pipewire-debian/files/7245856/pipewire_try_install_dependencies.txt)) returns an error that there is no release file.
Setting the repository as trusted seemed to fix it - `deb [trusted=yes] http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu buster main`

After this update seems to work - there are a couple 404's though.

But after that dependencies (both libfdk-aac1 & libfdkaac2) are still not found.

I also tried installing the specific versions from [MX/Debian upgrade pak](https://pastebin.com/S5duuECS), ie. `sudo apt install gstreamer1.0-pipewire=0.3.29-2~ubuntu18.04` but they're also not found.

Is Raspberry Pi OS not supported? From the readme it sounds like any debian based distro should work.

I'm not very experienced with linux so this could definitely be a lack of knowledge or something wrong on my part.

**To Reproduce**
* Follow the instructions on Raspberry Pi OS Buster (tested on Pi Model 3B+)
* add repository, try to run `sudo apt update`
* Fails because of  missing release file
* Set to trusted
* apt update - seems to work (sans a couple 404's 

**Expected behavior**
dependency packages are found and installed

**Desktop (please complete the following information):**
 - Distro: Raspberry Pi OS
 - Desktop Environment: No Desktop
 - Version 10 (buster)

**Comment by souravdas142** [comment]
output of 

`dpkg --print-architecture` and `dpkg --print-foreign-architectures` ??

**Comment by JonLevin25** [comment]
> output of
> 
> `dpkg --print-architecture` and `dpkg --print-foreign-architectures` ??

`dpkg --print-architecture` -> `armhf`
`dpkg --print-foreign-architectures` -> (No output>)

`sudo apt update` did show a 404 on `http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu buster/main armhf Packages` - is it not supported?

**Comment by souravdas142** [comment]
Yeah there is no build for `armhf` currently only `amd64` bit is supported. I'm trying to build for `armhf` if this is a easy way I'll update the lauchchpad with new build. Though you can install by adding `amd64` as foreign architecture. but All base and core packages will be installed AFAIK.

**Comment by JonLevin25** [comment]
Great, thanks!
Perhaps the readme could also note the `amd64` constraint, for future users.

> Though you can install by adding amd64 as foreign architecture. but All base and core packages will be installed AFAIK.

Just to make sure I understand correctly - you're saying the packages should be architecture-agnostic, so if I hack my way into getting the `amd64` ones they should work on an `armhf` system?

I'm probably missing the point here, but aren't there precompiled binaries that would be for x86-64, and therefore incompatible with arm?

**Comment by souravdas142** [comment]
ahh... right you are ref: https://www.reddit.com/r/debian/comments/4046yo/how_to_install_architecture_amd64_for/

And also I think I can't build for other architecture also , see : https://launchpad.net/~pipewire-debian/+archive/ubuntu/bionic-qt5125/+build/22230411 and https://launchpad.net/~pipewire-debian/+archive/ubuntu/bionic-qt5125/+build/22230412  If there is failed situation due to lack of dependencies then I can mange any how by avail them but there is no buildlog generated. In that situation I cant do anything. 

You can build by yourself by cloning this repo and build or cloning the upstream pipewire repo.

**Comment by JonLevin25** [comment]
Ah, that's too bad.
I think self-building is a bit too deep in the stack for me atm.
perhaps I'll wait until there is a stable arm version available to test.

Thanks for trying though :)

P.S. - as I mentioned above, it would be great to add the `arm64` constraint to the readme, as it could save future users the time of trying on a non-x86 system.

**Comment by souravdas142** [comment]
> P.S. - as I mentioned above, it would be great to add the arm64 constraint to the readme, as it could save future users the time of trying on a non-x86 system.

Yeah... sure..!!  Thanks for testing this.
