### ISSUE TITLE
Please enable 22.04 builds in the Launchpad PPA

### ISSUE THREAD

**Issue by eudoxos** [pipewire-debian/pipewire-debian#41]
I am running (beta) of Ubuntu 22.04 which includes pipewire in main repositories, but I am seeing some issues with Bluetooth (here we go again) and would be happy to install closer-to-upstream packages from your PPA. Could you enable the build for 22.04 in the PPA, if that is possible before the release? Thanks!

**Comment by souravdas142** [comment]
Done. version is 0.3.44 on PPA. Thanks for reporting...

**Comment by eudoxos** [comment]
Much appreciated, packages work well.
