### ISSUE TITLE
wireplumber: Error messages on  install

### ISSUE THREAD

**Issue by the-nic** [pipewire-debian/pipewire-debian#42]
During installation of wireplumber `0.4.7.r23.gb0ddd6f-1~ubuntu20.04` and pipewire `0.3.44-1~ubuntu20.04` I see the following messages

```
wireplumber (0.4.7.r23.gb0ddd6f-1~ubuntu20.04) wird eingerichtet ...
Failed to preset unit, file /etc/systemd/user/pipewire-session-manager.service already exists and is a symlink to /usr/lib/systemd/user/pipewire-media-session.service.
/usr/bin/deb-systemd-helper: error: systemctl preset failed on wireplumber.service: No such file or directory
Failed to restart wireplumber.service: Unit pipewire.service not found.
```

Its probably nothing to be concerned of

**Comment by souravdas142** [comment]
Hii @the-nic  I've updated the package... Can you confirm the error still exist or not by upgrading it ?

the changelog from previous :  

    -   -----  0.4.7.r24.gda023e1 ------
    - 
    - Disable '-Dsystemd-system-service' to match upstream
    - Update 'libwireplumber-0.4-0.symbols' file
    - Update 'wireplumber.install' file
    - 'debian/patches/revert_devenv.patch' removed

**Comment by the-nic** [comment]
Looks like it still exists:
```
wireplumber (0.4.7.r24.gda023e1-1~ubuntu20.04) wird eingerichtet ...
Failed to preset unit, file /etc/systemd/user/pipewire-session-manager.service already exists and is a symlink to /usr/lib/systemd/user/pipewire-media-session.service.
/usr/bin/deb-systemd-helper: error: systemctl preset failed on wireplumber.service: No such file or directory
```

**Comment by souravdas142** [comment]
Ok... Disable systemwide service for `pipewire-session-manager.service`

```bash
sudo systemctl --global disable --now  pipewire-session-manager.service
sudo systemctl --global disable --now wireplumber
```

then re-enable for your user

`sudo systemctl --user enable --now  wireplumber`

**Comment by souravdas142** [comment]
Ok...  @the-nic Can't reproducible here After Update...

ust Disable systemwide service for pipewire-session-manager.service

`sudo systemctl --global disable --now  pipewire-session-manager.service`
`sudo systemctl --global disable --now wireplumber`
`systemctl --user disable --now wireplumber`

remove and purge wireplumber

`sudo apt-get remove --purge wireplumber`

then reinstall and re-enable for your user only

`sudo apt-get install wireplumber`
`systemctl --user enable --now wireplumber`

**Comment by the-nic** [comment]
looks like that fixed it. apparently the initial installation with pipewire-media-session caused conflicts..

**Comment by souravdas142** [comment]
> looks like that fixed it. apparently the initial installation with pipewire-media-session caused conflicts..

Thanks for the confirmation.                      

One should disable `pipewire-session-manager.service` globally before installing wireplumber if user previously installed `pipewire-media-session`.
