### ISSUE TITLE
PipeWire 0.3.45 (2022-02-03) no sound devices

### ISSUE THREAD

**Issue by FerdiScholten** [pipewire-debian/pipewire-debian#43]
PipeWire 0.3.45 (2022-02-03) no sound devices

Since several months my Thinkpad T540p has been working flawless with pipewire and wireplumber as full replacement for pulseaudio on ubuntu 21.10

However the latest update of pipewire, no sound devices are found, reverting to pulseaudio solves the issue immediately. There were no changes in configuration whatsoever.

observations: All the pipewire services are running normally without errors, wireplumber is running normaly without errors, pavucontrol shows no output devices when using pipewire, volume controls in gnome settings are disabled en show no output devices. When opening any program using sound the following loglines appear in syslog: `Feb  6 00:36:40 Biodanza01 pipewire-pulse[1246]: mod.protocol-pulse: client 0x55f007895d80 [libcanberra]: ERROR command:-1 (invalid) tag:3 error:25 (Input/output error)
`
using pipewire and wireplumber from https://github.com/pipewire-debian/pipewire-debian

running Pulseaudio:

```
pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 15
Tile Size: 65472
User Name: ferdi
Host Name: Biodanza01
Server Name: pulseaudio
Server Version: 15.0
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_1b.0.analog-stereo
Default Source: alsa_input.pci-0000_00_1b.0.analog-stereo
Cookie: 6010:24c6
```

running pipewire:

```
pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 40
Tile Size: 65472
User Name: ferdi
Host Name: Biodanza01
Server Name: PulseAudio (on PipeWire 0.3.45)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: @DEFAULT_SINK@
Default Source: @DEFAULT_SOURCE@
Cookie: 21e9:6107
```

**Comment by souravdas142** [comment]
Hii @FerdiScholten  Thanks for informing... However Its not the right place for Upstream bug reporting... i've seen you already created https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2111  
and also possible related issue : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2108, https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2107

I'm following on gitlab... If some commit/MR address that I'll upload it to testing branch https://launchpad.net/~pipewire-debian/+archive/ubuntu/testing from where you can test that. Thanks.

**Comment by FerdiScholten** [comment]
The issue arises when the kernel is not built with CONFIG_SND_VERBOSE_PROCFS enabled.
Apparently this is fixed in current master.
options are, downgrade to 3.44, upgrade to git-master or recompile kernel with CONFIG_SND_VERBOSE_PROCFS enabled
