### ISSUE TITLE
Bluetooth sound does not work until alsa-utils are removed

### ISSUE THREAD

**Issue by A-Joshi** [pipewire-debian/pipewire-debian#44]
Followed the installation instructions on Ubuntu  _impish_ and pipewire seemed to be working fine with wired speakers etc. Bluetooth was adifferent story: headsets/speakers would connect but show no audio profiles, would not show up in the audio devices as input or output. 

 After a lot of reinstalls and trial and error found the solution based on [Ask Fedora question](https://ask.fedoraproject.org/t/i-broke-my-audio-with-the-last-update-no-sound-wireplumber-involved-and-others/19738) - need to remove alsa-utils if they are installed. Might want to make a note in the instructions about bluetooth.
 `apt remove --purge alsa-utils bluez-alsa-utils`

**Comment by souravdas142** [comment]
@A-Joshi 
Raise an issue : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/new 

It seems not an issue with `alsa-utils`. According to [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2058#note_1228129) There is no file collisions between other packages. please consult with upstream, until devs not confirm this... I can't do anything.

**Comment by souravdas142** [comment]
Can't reproduce here, Reopen again if the issue exist for others also
