### ISSUE TITLE
libxfixes: missing i386 package

### ISSUE THREAD

**Issue by the-nic** [pipewire-debian/pipewire-debian#46]
I have steam installed which uses 32-bit packages. The new xfixes version then breaks these packages:

```
The following packages will be upgraded: 
  gstreamer1.0-pipewire libpipewire-0.3-0 libpipewire-0.3-modules libspa-0.2-bluetooth libspa-0.2-modules libxfixes3{b} pipewire pipewire-audio-client-libraries pipewire-bin pipewire-pulse 
10 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 2169 kB of archives. After unpacking 24.6 kB will be used.
The following packages have unmet dependencies:
 libxfixes3 : Breaks: libxfixes3:i386 (!= 1:6.0.0-3~ubuntu20.04) but 1:5.0.3-2 is installed
 libxfixes3:i386 : Breaks: libxfixes3 (!= 1:5.0.3-2) but 1:6.0.0-3~ubuntu20.04 is to be installed
```

Looks like adding the `:i386` arch could solve this issue

**Comment by souravdas142** [comment]
I'll enable i386 packages if it allows me, give me some time. thanks for reporting

**Comment by the-nic** [comment]
Was the upgrade of libxfixes even needed on 20.04? The changes seem rather minimal

**Comment by souravdas142** [comment]
@the-nic  yeah... Actually PipeWire itself added this  dependency (See MR: https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1167) libXfixes (>= 6.0.0). But all ubuntu (< 22.04) have 5.0.0 or something So that we need to upgrade on all ubuntu which are less than 22.04 right ?

**Comment by the-nic** [comment]
@souravdas142 Thanks for the reference! You're right, if pipewire uses `xfixes`, version >= 6 is required. However, the dependency seems optional at compile-time:

``` 
xfixes_dep = dependency('xfixes', required : get_option('x11-xfixes'), version: '>= 6')
cdata.set('HAVE_XFIXES_6', xfixes_dep.found())
```

So, building without xfixes should work, at least until the i386 solution is resolved.

**Comment by souravdas142** [comment]
No, i386 is allowed for this package what I observed, even it got built, I'm just about to publish them.

And yes its optional, but PipeWire from this repo aims to enable all module to test and help devs.

**Comment by the-nic** [comment]
If it works, then perfect :) I was just proposing this in case it didnt work.

**Comment by souravdas142** [comment]
Hi can you now try to upgrade, i386 architecture for libXfixes package just got published. So if it still doesn't work, report me back. Thanks.

**Comment by the-nic** [comment]
Works! Thanks for fixing this! Closing this ticket
