### ISSUE TITLE
Public key unavailable

### ISSUE THREAD

**Issue by merjay** [pipewire-debian/pipewire-debian#48]
Tried to install pipewire today buy I get: NO_PUBKEY 25088A0359807596.

**Comment by souravdas142** [comment]
did you update repo list with `sudo apt-get update` or `sudo apt update` before you are actually going to upgrade. "NO_PUBKEY" its generally launchpad issue.

**Comment by merjay** [comment]
Yes, I got the error when I executed ```sudo apt-get update```. I searched for the key in http://keyserver.ubuntu.com/ and it also says "Not found".

**Comment by souravdas142** [comment]
Its launchpad error... but what you can do is readding ppa again, I mean first remove PPA and add again, then try to update again.

**Comment by souravdas142** [comment]
What is your OS, version give all details ?

**Comment by merjay** [comment]
I'm on Debian 11.2, and I removed the PPA and tried to run ```gpg -v --keyserver keyserver.ubuntu.com --recv-keys 25088A0359807596``` only to get: "gpg: keyserver receive failed: Server indicated a failure".

**Comment by souravdas142** [comment]
Can you see the [bullseye.log](https://github.com/pipewire-debian/pipewire-debian/files/8199517/bullseye.log) Do I've any errors ? Did you read all instructions before proceeding ? You seems not good to open an issue properly, Like I've created a template for this, you don't even think to use it right ? thanks for wasting my whole evening.

**Comment by merjay** [comment]
I tried first with ```add-apt-repository``` according to instructions, but it did not work. I then tried without it according to the instructions when  ```add-apt-repository``` is not available, but I was not able to proceed after the first command: ```# gpg -v --keyserver keyserver.ubuntu.com --recv-keys 25088A0359807596
gpg: keyserver receive failed: Server indicated a failure```. After seeing this I added -v to gpg but it did not give me more information. Third step I tried was to go to the browser and search for the key 25088A0359807596 in https://keyserver.ubuntu.com which also did not help me as the page only said "Not Found" when I searched for the key. Then I found this https://superuser.com/questions/620765/sudo-apt-key-adv-keyserver-keyserver-ubuntu-com-recv-7f0ceb10-command-return and it helped me solve the issue. When searching for the key in the web browser you need to add 0x before 25088A0359807596 and it was able to find it. Then in the console i was also able to find the key using this command: ```gpg -v --keyserver hkp://keyserver.ubuntu.com:80 --search-keys 25088A0359807596```. I'm **honestly** sorry and ashamed for wasting your time, I was fooled by both using gpg and searching for the key in the web browser without '0x' that made me think something was wrong with the key in the first place.

**Comment by souravdas142** [comment]
@merjay  So if your issue is solved can we close this ?

**Comment by merjay** [comment]
@souravdas142 Yes, I'm now able to use the key and go on with my installation. Thank you for your help!
