### ISSUE TITLE
pipewire.service is masked - no sound after update

### ISSUE THREAD

**Issue by Ethanol6** [pipewire-debian/pipewire-debian#49]
I recently ran updates on my system and now I have no sound. Pulse is masked as the instructions tell me to do. But now, if I try to restart pipewire with `systemctl --user --now enable pipewire{,-pulse}.{socket,service}` I get the error `Failed to enable unit: Unit file /etc/xdg/systemd/user/pipewire.socket is masked.'

Running `systemctl --user unmask pipewire.socket` seems to work, there's no errors but if I try again to enable pipewire it tells me it's still masked.

**Comment by souravdas142** [comment]
**Fill below Template** 
------




**If you Completed all troubleshoot options, check below**     
- [ ]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [ ]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?


**Desktop (please complete the following information):**
 - Distro: [e.g. Ubuntu]
 - Desktop: Environment [e.g. Gnome]
 - Version: [e.g. 20.04]
 - PipeWire Related packages Version: [pipewire, wireplumber, libcamera, etc.] 
 - Kernel version: 


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:


**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
(snapshot of PW related services or anything)



**Journal log and status of related services**
Add any other context about the problem here.


**Additonal Information (If applicable):**                                          
.                                          
.                                          
.

**Comment by Ethanol6** [comment]
I rolled back to a previous days snapshot with Timeshift. Pipewire started working again. I just ran the updates again and now it is working fine. Pipewire version 0.3.48.

Sorry to waste your time. Not sure what went wrong.

**Comment by mathieujobin** [comment]
I have similar problem after upgrading and rebooting...
using ubuntu 22.10 though

```
$ dpkg -l | grep -i ^i.*pipew 
ii  gstreamer1.0-pipewire:amd64                      0.3.58-2ubuntu1                             amd64        GStreamer 1.0 plugin for the PipeWire multimedia server
ii  libkpipewire5                                    5.26.2-0ubuntu1~ubuntu22.10~ppa2            amd64        KDE's Pipewire libraries - libkpipewire5 library
ii  libkpipewirerecord5                              5.26.2-0ubuntu1~ubuntu22.10~ppa2            amd64        KDE's Pipewire libraries - libkpipewirerecord5
ii  libpipewire-0.3-0:amd64                          0.3.58-2ubuntu1                             amd64        libraries for the PipeWire multimedia server
ii  libpipewire-0.3-common                           0.3.58-2ubuntu1                             all          libraries for the PipeWire multimedia server - common files
ii  libpipewire-0.3-modules:amd64                    0.3.58-2ubuntu1                             amd64        libraries for the PipeWire multimedia server - modules
ii  libspa-0.2-bluetooth:amd64                       0.3.58-2ubuntu1                             amd64        libraries for the PipeWire multimedia server - bluetooth plugins
ii  libspa-0.2-modules:amd64                         0.3.58-2ubuntu1                             amd64        libraries for the PipeWire multimedia server Simple Plugin API - modules
ii  pipewire:amd64                                   0.3.58-2ubuntu1                             amd64        audio and video processing engine multimedia server
ii  pipewire-bin                                     0.3.58-2ubuntu1                             amd64        PipeWire multimedia server - programs
ii  pipewire-pulse                                   0.3.58-2ubuntu1                             amd64        PipeWire PulseAudio daemon
ii  qml-module-org-kde-pipewire                      5.26.2-0ubuntu1~ubuntu22.10~ppa2            amd64        KDE's Pipewire libraries - QML module
ii  wireplumber                                      0.4.12-1                                    amd64        modular session / policy manager for PipeWire
```

**Comment by souravdas142** [comment]
ubuntu 22.10 has latest version of PW, is not it ?

**Comment by mathieujobin** [comment]
0.3.58 appears more recent than OP's 0.3.48, but I did not double-check if it is the latest. Most likely, as it just got officially released a few days ago.

What's weird, is my sound did work after distro upgrade. But broke on last apt-upgrade and reboot.

I wonder if I am not missing a package or need to delete some pulseaudio legacy ones?

**Comment by mathieujobin** [comment]
ok, I have not rebooted, so I'm not sure its 100% solved.
but I deleted the `pulseaudio` and `libpulseaudio` packages.
and pipewire.service was out. so I just start and enabled. 
and my audio device is good

```
mathieu:auth :-( 1 (develop) $ systemctl --user status pipewire.service
○ pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; preset: enabled)
     Active: inactive (dead)
TriggeredBy: ○ pipewire.socket
mathieu:auth :-( 1 (develop) $ systemctl --user start pipewire.service
mathieu:auth :-) (develop) $ systemctl --user status pipewire.service
● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; preset: enabled)
     Active: active (running) since Fri 2022-10-28 08:48:54 JST; 1s ago
TriggeredBy: ● pipewire.socket
   Main PID: 18858 (pipewire)
      Tasks: 1 (limit: 23698)
     Memory: 2.1M
        CPU: 18ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─18858 /usr/bin/pipewire

Oct 28 08:48:54 mathieu-FMVWB3U28 systemd[1995]: Started PipeWire Multimedia Service.
mathieu:auth :-) (develop) $ lspci | grep audio
mathieu:auth :-( 1 (develop) $ systemctl --user status pipewire.service
● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; preset: enabled)
     Active: active (running) since Fri 2022-10-28 08:48:54 JST; 10s ago
TriggeredBy: ● pipewire.socket
   Main PID: 18858 (pipewire)
      Tasks: 2 (limit: 23698)
     Memory: 5.0M
        CPU: 31ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─18858 /usr/bin/pipewire

Oct 28 08:48:54 mathieu-FMVWB3U28 systemd[1995]: Started PipeWire Multimedia Service.
mathieu:auth :-) (develop) $ systemctl --user enable pipewire.service
Created symlink /home/mathieu/.config/systemd/user/default.target.wants/pipewire.service → /usr/lib/systemd/user/pipewire.service.
Created symlink /home/mathieu/.config/systemd/user/sockets.target.wants/pipewire.socket → /usr/lib/systemd/user/pipewire.socket.
```

These links can also be helpful

https://bbs.archlinux.org/viewtopic.php?id=265269

https://www.reddit.com/r/archlinux/comments/m7yc6j/pipewire_0324_no_audio_devices_found/

https://ask.fedoraproject.org/t/pipewire-doesnt-actually-recognize-any-sound-outputs-devices/17021

**Comment by pwolfe8** [comment]
had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:

```
sudo apt reinstall pipewire pipewire-bin pipewire-pulse
systemctl --user --now enable pipewire pipewire-pulse
```

**Comment by HeyItsAditya** [comment]
> had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:
> 
> ```
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> systemctl --user --now enable pipewire pipewire-pulse
> ```

thanks that worked for saviour

**Comment by thunderock** [comment]
> had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:
> 
> ```
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> systemctl --user --now enable pipewire pipewire-pulse
> ```

this worked on pop os !

**Comment by satmandu** [comment]
On Ubuntu 22.10 I had to do this once:

```
sudo apt reinstall pipewire pipewire-bin pipewire-pulse
```
Then for every user I had to do this:
```
systemctl --user unmask pipewire-pulse
systemctl --user unmask pipewire-pulse.socket
systemctl --user --now enable pipewire pipewire-pulse
```
Then `pactl info` gave me the correct information

**Comment by tsakishii** [comment]
> had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:
> 
> ```
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> systemctl --user --now enable pipewire pipewire-pulse
> ```

It worked for me on Pop!_OS 22.04

**Comment by dipada** [comment]
> had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:
> 
> ```
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> systemctl --user --now enable pipewire pipewire-pulse
> ```

After kernel patching and update, pipewire was masked. (Pop os 22.04). Following pop troubleshooting doesn't fix the issue.

This worked for me too!

**Comment by marronjo** [comment]
this worked, thank you sm

**Comment by akolundzic** [comment]
Hi, 
thank you for the advice but that has not fixed my problems. 
I still get the same error again and again.

**Comment by wilbura009** [comment]
> had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:
> 
> ```
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> systemctl --user --now enable pipewire pipewire-pulse
> ```

Same problem on:

OS: Pop 22.04 jammy
Kernel: x86_64 Linux 6.2.6-76060206-generic

But this worked. I did have to reboot as well. Thank you!

**Comment by Peterdes** [comment]
> On Ubuntu 22.10 I had to do this once:
> 
> ```
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> ```
> 
> Then for every user I had to do this:
> 
> ```
> systemctl --user unmask pipewire-pulse
> systemctl --user unmask pipewire-pulse.socket
> systemctl --user --now enable pipewire pipewire-pulse
> ```
> 
> Then `pactl info` gave me the correct information

After a recent upgrade, I did this and it fixed the issue as well.

**Comment by CaneRandagio1983** [comment]
> 

this works on ubuntu 23.04

**Comment by DudeNamedBen** [comment]
> had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:
> 
> ```
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> systemctl --user --now enable pipewire pipewire-pulse
> ```

This just happened to me.
Thanks so much for the post

**Comment by TiagoRibeiro25** [comment]
> had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:
> 
> ```
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> systemctl --user --now enable pipewire pipewire-pulse
> ```

Thanks a lot ❤️

**Comment by TCROC** [comment]
> > had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:
> > ```
> > sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> > systemctl --user --now enable pipewire pipewire-pulse
> > ```
> 
> Thanks a lot ❤️

This fixed it for me as well!  Thank you! :)

**Comment by Kreijstal** [comment]
this didnt work, unfortunately, it kept still being masked.

> had this same problem with unmask not fixing it. Followed another thread that suggested this that finally fixed my problem:
> 
> ```
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> systemctl --user --now enable pipewire pipewire-pulsea
> ```
