### ISSUE TITLE
pipewire.service "cannot allocate memory" errors with kernel 5.17

### ISSUE THREAD

**Issue by comrade-meowski** [pipewire-debian/pipewire-debian#53]
I have a workstation running Ubuntu 21.10 with pipewire+wireplumber set up as per https://pipewire-debian.github.io/pipewire-debian/. Zero problems for six months plus with pipewire so far. All 5.17 series kernels I've tested so far however start throwing memory errors with the pipewire.service before long:

Apr 02 06:33:37 failbot pipewire[1036652]: spa.alsa: set_hw_params: Cannot allocate memory
Apr 02 06:33:37 failbot pipewire[1036652]: pw.node: (alsa_output.pci-0000_2a_00.3.analog-stereo-42) suspended -> error (Start err>
Apr 02 06:33:37 failbot pipewire[1036652]: spa.alsa: set_hw_params: Cannot allocate memory
Apr 02 06:33:58 failbot pipewire[1036652]: pw.link: 0x55c327d29430: one of the nodes is in error out:suspended in:error
Apr 02 06:33:58 failbot pipewire[1036652]: pw.link: 0x55c327d2f5c0: one of the nodes is in error out:suspended in:error

Restarting the service will temporarily re-enable sound, usually until another application (browser video, mpv, etc) is started and pipewire.service will fail with the same errors. Dropping caches or flushing ZFS ARC to recover large amounts of RAM (or just rebooting) will buy another few hours or normal operation but as soon as the system fills up ~90% of memory pipewire.service will fail again. Workstation has 32Gb of RAM + optionally a 32Gb swap file so even with heavy RAM utilisation when pipewire.service fails with "Cannot allocate memory" there can be 6Gb+ of physical RAM still free. 

This is always reproducible with any 5.17 kernel. Rebooting into any 5.16 or earlier kernel returns immediately to normal operation and long uptimes with continuous 90%+ RAM utilisation and zero pipewire.service failures. 

Of course this could be an upstream pipewire or kernel issue but I thought I'd start here.

**Comment by souravdas142** [comment]
Sorry for late reply but have you tested yet [results from google search](https://www.google.com/search?q=set_hw_params%3A+Cannot+allocate+memory&oq=set_hw_params%3A+Cannot+allocate+memory) ? I mean there are lots of results i can see which may be similar to this issue ?? 

Any Special requirements/reason you have switched to latest linux ? As you mentioned linux 5.16 have no problem right ? You can stay at 5.16 for now.

Also suggesting open a bug report to upstream(with all logs) if above could't solve the issue, For the moment I have no time and a ubuntu 21.10 iso with 5.17 for reproducing this Thank you.

**Comment by souravdas142** [comment]
follow : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2272

**Comment by comrade-meowski** [comment]
Ah ha, finally some other people hitting the same bug and reporting it upstream. Thanks for spotting that and letting me know, I'll pitch in there.

I find myself in the same position as the second poster having gone pretty far down the rabbit hole chasing it - I'd built multiple patched 5.17 kernels fiddling with options and was working on a reproducer before opening a pipewire issue.

It's specifically an interaction between pipwire itself (wireplumber vs pipewire-media-session don't make any difference) and any 5.17 kernel on systems with high memory utilisation.

Temporarily switching back to pulseaudio on 5.17 series kernels works fine in the interim.

**Comment by souravdas142** [comment]
> I'll pitch in there.

Yeah Sure... 

And who are affected with this please  follow : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2272

As its now an upstream issue, closing here. Thank you.

**Comment by comrade-meowski** [comment]
Agreed and many thanks for your help.

**Comment by pizzadude** [comment]
Thank you for reporting this, I was having this problem in Fedora 36 and I'm glad I found a workaround.
