### ISSUE TITLE
Unable to locate package blueman-git

### ISSUE THREAD

**Issue by TriplEight** [pipewire-debian/pipewire-debian#58]
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: Ubuntu
 - Desktop: Environment Gnome
 - Version: 22.04
 - PipeWire Related packages Version: pipewire 0.3.50, wireplumber 0.4.9.r8.g812fc9b-1~ubuntu22.04
 - Kernel version: 5.15.0-27-generic

**Describe the bug**
Following the manual I faced some bugs:

```bash
$ sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,bin,locales,tests}}

The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libspa-0.2-jack : Depends: libspa-0.2-modules (= 0.3.48-1ubuntu1) but 0.3.50.r15.gc73c852-1~ubuntu22.04 is to be installed
 pipewire-tests : Depends: pipewire (= 0.3.48-1ubuntu1) but 0.3.50.r15.gc73c852-1~ubuntu22.04 is to be installed
                  Depends: libpipewire-0.3-0 (= 0.3.48-1ubuntu1) but 0.3.50.r15.gc73c852-1~ubuntu22.04 is to be installed
E: Unable to correct problems, you have held broken packages.
```
What to do with the newer versions?

and

```bash
$ apt install blueman-git

Unable to locate package blueman-git
```
How to install it properly, after removing `blueman` my Bluetooth misbehaves.

**To Reproduce**
Try the mentioned commands

**Expected behavior**

**Comment by souravdas142** [comment]
Most probably you have to enable `Universe` repo. After enabling make repo sync locally. then try to upgrade. 

For `blueman-git` package let me see what is the issue. Give me some times.

**Comment by souravdas142** [comment]
@TriplEight   For `blueman-git` there is also no issue. Please sync repo. Confirm me this is working or not ?

**Comment by TriplEight** [comment]
@souravdas142 I've added universe and multiverse repos, it did not help for neither of the problems

**Comment by souravdas142** [comment]
output of `sudo apt install libspa-0.2-modules` ?

**Comment by TriplEight** [comment]
> output of `sudo apt install libspa-0.2-modules` ?

`libspa-0.2-modules is already the newest version (0.3.50.r15.gc73c852-1~ubuntu22.04).`

**Comment by souravdas142** [comment]
try to install `libspa-0.2-modules`, `pipewire`, `libpipewire-0.3-0`  package **one by one**, and give full output what  shows on terminal, even paste which command you put ?

**Comment by TriplEight** [comment]
```
$ sudo apt install libspa-0.2-modules
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libspa-0.2-modules is already the newest version (0.3.50.r15.gc73c852-1~ubuntu22.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ sudo apt install pipewire
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pipewire is already the newest version (0.3.50.r15.gc73c852-1~ubuntu22.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ sudo apt install libpipewire-0.3-0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libpipewire-0.3-0 is already the newest version (0.3.50.r15.gc73c852-1~ubuntu22.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by souravdas142** [comment]
sorry problem is not reproducible here.... Meanwhile 0.3.51 was up, can you please make a repo sync again and try with latest version ?

**Comment by souravdas142** [comment]
Moreover If you had tried some other pipewire package from different PPA try to replace them with this one. You can do that with `ppa-purge` program

**Comment by TriplEight** [comment]
Oh, this finally made me think in the right direction. Since I've been upgrading to Ubuntu 22.04, it had my PPAs reset to default ones. While this fact has slipped from me, I didn't apply the very first line of your manual relying upon that I've already had it in the system:
`sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream`
Thanks, now everything is resolved for me.

**Comment by souravdas142** [comment]
closing
