### ISSUE TITLE
Pipewire ppa breaks ppa-purge

### ISSUE THREAD

**Issue by gfl43r9nd** [pipewire-debian/pipewire-debian#59]
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: Ubuntu
 - Desktop: Environment: Gnome Shell
 - Version: 22.04
 - PipeWire Related packages Version: pipewire 0.3.50.r15.gc73c852-1~ubuntu22.04
 - Kernel version: 5.15.0-27-generic

**Describe the bug**
I recently upgraded to Ubuntu 22.04. I followed these instructions to add the ppa and install pipewire again https://pipewire-debian.github.io/pipewire-debian/ However, I noticed that after doing this I could no longer remove ppa's using ppa-purge. Turns out this is because the version of ppa-purge in the pipewire upstream ppa (https://launchpad.net/~pipewire-debian/+archive/ubuntu/pipewire-upstream ) doesn't have the fix for looking for ppas in launchpadcontent.net and not launchpad.net (https://bugs.launchpad.net/ubuntu/+source/ppa-purge/+bug/19

**Comment by souravdas142** [comment]
Hi @gfl43r9nd  fix version has been updated on launchpad, can you please make a repo sync and  check all your issue has been solved or not ?

**Comment by hellocatfood** [comment]
I had this same problem and the recent update seems to fix it

**Comment by souravdas142** [comment]
@hellocatfood  Thanks for your confirmation. 
closing
