### ISSUE TITLE
💥New upstream release 0.3.32💥

### ISSUE THREAD

**Issue by pipewire-debian** [pipewire-debian/pipewire-debian#6]
## 💥 New upstream release 0.3.32 💥

   **CHANGELOGS -**

**Debian Package -**

  - roc-toolkit splitted into libroc, libroc-dev, roc

  - openfec renamed to libopenfec, bump to 1.4.2.4 (roc-streaming fork)

**PipeWire -**

  - Real-time priority handling for threads was reworked. Freewheeling
    will now drop RT priorities to avoid being killed.
  - Problems with filter chains and echo-cancel being linked in a loop
    was fixed.
  - alsamixer should now be able to see the mixer controls again.
  - JACK has seen some latency reporting improvements that make Ardour
    report latencies correctly.
  - Many bugfixes and improvements.
  - For more : https://gitlab.freedesktop.org/pipewire/pipewire/-/releases

**Comment by pablodz** [comment]
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases#0.3.32  👀👀👀👀👀👀

**Comment by souravdas142** [comment]
@pablodz  wait some hours, It will be up.

**Comment by souravdas142** [comment]
@pablodz  sorry... but I'll up new version tomorrow. I want to wait for some time.. pipewire is not compiling, this is an upstream issue..  The release will not be from the tag 0.3.32 but with some more commits.

**Comment by pablodz** [comment]
@souravdas142 don't worry, take your time

**Comment by maxorbase** [comment]
Tried to install from PPA, everything is ok and pipewire update to the latest version 
libpipewire-0.3-0 is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
But the pactl info show the version is used 
Server Name: PulseAudio (on PipeWire 0.3.25)
and the new lib such libpipewire-module-filter-chain doesn't include 
is this true?? Or not how to update correctly to the newest version ?

**Comment by souravdas142** [comment]
@maxorbase  Assuming you did read all instructions from readme. whatever I wan't not to make this convertion long, so just giving the instruction here. do the command `sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,media-session,bin,locales,tests}}` and enable , restart the all pipewire based services. `systemctl --user --now enable pipewire{,-pulse}.{socket,service} pipewire-media-session.service` and then `systemctl --user restart pipewire{,-pulse}.{socket,service} pipewire-media-session.service`

**Comment by maxorbase** [comment]
I did everything in README and again do this for your instruction 
all package installed 
gstreamer1.0-pipewire is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
libpipewire-0.3-0 is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
libpipewire-0.3-dev is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
libpipewire-0.3-modules is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
libspa-0.2-bluetooth is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
libspa-0.2-dev is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
libspa-0.2-jack is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
libspa-0.2-modules is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
pipewire is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
pipewire-audio-client-libraries is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
pipewire-bin is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
pipewire-locales is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
pipewire-media-session is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
pipewire-pulse is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
pipewire-tests is already the newest version (0.3.32+dfsg1-1ubuntu21.04).
After all pactl info show still
Server Name: PulseAudio (on PipeWire 0.3.25)

**Comment by souravdas142** [comment]
delete `/etc/pipewire` and `~/.config/pipewire`.disable pipewire services for user `systemctl --user disable --now ...` then enable `systemctl --user enable --now ...` if still not solve, restart your machine...

**Comment by maxorbase** [comment]
1-delete all config, disable all service and restart doesn't work 
2-purge pipewire and pulsaudio, reinstall both  
3-purge pipewire and install debian exprimental version 
4- purge debian version and delete all config and folder, reinstall agian from ppa 
all of this doesn't work 
I'm confusing how this happened

**Comment by pablodz** [comment]
> 1-delete all config, disable all service and restart doesn't work
> 2-purge pipewire and pulsaudio, reinstall both
> 3-purge pipewire and install debian exprimental version
> 4- purge debian version and delete all config and folder, reinstall agian from ppa
> all of this doesn't work
> I'm confusing how this happened

After install or reinstall you'll need to reboot your PC

**Comment by maxorbase** [comment]
> > 1-delete all config, disable all service and restart doesn't work
> > 2-purge pipewire and pulsaudio, reinstall both
> > 3-purge pipewire and install debian exprimental version
> > 4- purge debian version and delete all config and folder, reinstall agian from ppa
> > all of this doesn't work
> > I'm confusing how this happened
> 
> After install or reinstall you'll need to reboot your PC

After any change even small change reboot pc

**Comment by souravdas142** [comment]
any status ? @pablodz

**Comment by souravdas142** [comment]
any status @maxorbase 

your distro name, version and desktop ?

**Comment by souravdas142** [comment]
@maxorbase 
> Server Name: PulseAudio (on PipeWire 0.3.25)

From this line, Its clear pipewire still using its older server ? did you remove all configs from both /etc/ and ~/.config ? did you disable all services using `systemctl --user disable ...` and enable them after installing latest version from this ppa ? 

There is no issue here.

**Comment by maxorbase** [comment]
> any status @maxorbase
> 
> your distro name, version and desktop ?

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-25-generic
OS Type: 64-bit
Graphics Platform: X11

**Comment by maxorbase** [comment]
> @maxorbase
> 
> > Server Name: PulseAudio (on PipeWire 0.3.25)
> 
> From this line, Its clear pipewire still using its older server ? did you remove all configs from both /etc/ and ~/.config ? did you disable all services using `systemctl --user disable ...` and enable them after installing latest version from this ppa ?
> 
> There is no issue here.

I think I found the problem
there are two patches for services when i search for the pipewire-media-session.service and others services 
1-/usr/lib/systemd/user/ 
the services in this location is new and located pipewire in ExecStart=/usr/bin/pipewire
2/usr/local/lib/systemd/user/
the date of modified service in this location is too old(When the system was installed) and  located pipewire in ExecStart=/usr/local/bin/pipewire

The systemctl --user enable .... Created symlink from second location service, Which is both an older pipewire version and an older service

the pipewire and other  like pw-cli, pipewire-media-session ..... located in /usr/local/bin/ and module located in /usr/local/lib/x86_64-linux-gnu/pipewire-0.3/ is too old 
unlike the version stored in /usr/lib/ and module  /usr/lib/x86_64-linux-gnu/pipewire-0.3/ is new and have all module in pipewire 0.3.32

**Comment by souravdas142** [comment]
@maxorbase  I'm curious about from where you get 0.3.25 ? Its not from official one right ? the package was build with `PREFIX=/usr/local` . Its not the behaviour from official or mine. I am suspecting it was install from other external source right ? the packages from this ppa is fully compatible with official one not from the external  bad built. Now it seems to me I was wasted my time in this. So please stop wasting my time further. Thank you.

**Comment by maxorbase** [comment]
> @maxorbase I'm curious about from where you get 0.3.25 ? Its not from official one right ? the package was build with `PREFIX=/usr/local` . Its not the behaviour from official or mine. I am suspecting it was install from other external source right ? the packages from this ppa is fully compatible with official one not from the external bad built. Now it seems to me I was wasted my time in this. So please stop wasting my time further. Thank you.

Thank you for such a wonderful gift , remove all pipewire file in local and eveything back to normal
