### ISSUE TITLE
wireplumber 0.4.10-1 breaks bluetooth audio

### ISSUE THREAD

**Issue by madushan1000** [pipewire-debian/pipewire-debian#60]
**If you Completed all troubleshoot options, check below**     
- [ X ]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [ X ]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: Ubuntu
 - Desktop: Gnome
 - Version: 22.04
 - PipeWire Related packages Version: pipewire=0.3.51-1, wireplumber=0.4.10-1
 - Kernel version: 5.15.0-30-generic

**Describe the bug**
Upgrading to wireplumber 0.4.10-1 breaks bluetooth audio. Related logs bellow

**To Reproduce**
install wireplumber 0.4.10-1 and restart the wireplumber service

**Expected behavior**
for bluetooth audio to work.

**Journal log and status of related services**
bluetooth.service logs
```
May 17 10:12:25 nb0279 bluetoothd[3830]: Starting SDP server
May 17 10:12:25 nb0279 bluetoothd[3830]: Bluetooth management interface 1.21 initialized
May 17 10:12:25 nb0279 bluetoothd[3830]: Battery Provider Manager created
May 17 10:12:25 nb0279 bluetoothd[3830]: Adv Monitor Manager created with supported features:0x00000000, enabled features:0x00000000, max number >
May 17 10:12:34 nb0279 bluetoothd[3830]: src/service.c:btd_service_connect() a2dp-sink profile connect failed for XXXXXXX: Protocol not available
May 17 10:12:34 nb0279 bluetoothd[3830]: Path / reserved for Adv Monitor app :1.145
May 17 10:12:34 nb0279 bluetoothd[3830]: Adv Monitor app :1.145 disconnected from D-Bus
May 17 10:17:37 nb0279 bluetoothd[3830]: src/service.c:btd_service_connect() a2dp-sink profile connect failed for XXXXXXX: Protocol not available
May 17 10:17:37 nb0279 bluetoothd[3830]: Path / reserved for Adv Monitor app :1.158
May 17 10:17:37 nb0279 bluetoothd[3830]: Adv Monitor app :1.158 disconnected from D-Bus
May 17 10:17:58 nb0279 bluetoothd[3830]: src/service.c:btd_service_connect() a2dp-sink profile connect failed for XXXXXXX: Protocol not available
May 17 10:17:58 nb0279 bluetoothd[3830]: Path / reserved for Adv Monitor app :1.159
May 17 10:17:58 nb0279 bluetoothd[3830]: Adv Monitor app :1.159 disconnected from D-Bus
May 17 10:20:06 nb0279 bluetoothd[3830]: src/service.c:btd_service_connect() a2dp-sink profile connect failed for XXXXXXX: Protocol not available
May 17 10:20:06 nb0279 bluetoothd[3830]: Path / reserved for Adv Monitor app :1.169
May 17 10:20:06 nb0279 bluetoothd[3830]: Adv Monitor app :1.169 disconnected from D-Bus
May 17 10:20:25 nb0279 bluetoothd[3830]: src/service.c:btd_service_connect() a2dp-sink profile connect failed for XXXXXXX: Protocol not available
May 17 10:20:25 nb0279 bluetoothd[3830]: Path / reserved for Adv Monitor app :1.170
May 17 10:20:25 nb0279 bluetoothd[3830]: Adv Monitor app :1.170 disconnected from D-Bus
May 17 10:24:55 nb0279 bluetoothd[3830]: src/service.c:btd_service_connect() a2dp-sink profile connect failed for XXXXXXX: Protocol not available
May 17 10:24:55 nb0279 bluetoothd[3830]: Path / reserved for Adv Monitor app :1.173
```

**Additonal Information (If applicable):**                                          
* Downgrading to wireplumber 0.4.8(from ubuntu repos, not the ppa) fixes the issue. I guess wirepumber 0.4.9 form the ppa will work too but I can't test it because the ppa doesn't keep the old versions.
* Just downgrading wireplumber works, so I don't think this is a pipewire or bluez bug.

**Comment by souravdas142** [comment]
https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/254 check and report me back.

**Comment by madushan1000** [comment]
Thanks, didn't notice it at all in their bug tracker. will give a try.

**Comment by souravdas142** [comment]
> I can't test it because the ppa doesn't keep the old versions.

I noticed too and have no Idea why they stopped keeping those files. Probably I should ask on launchpad itself.

**Comment by madushan1000** [comment]
Adding `bluez_monitor.enabled = true` to my `.config/wireplumber/./bluetooth.lua.d/50-bluez-config.lua` worked! I guess adding that line to the global config in `/etc` or `/usr/share` will work too. 

I think this bug happens because I don't split the wirepliumber config properly. But well, you only have so much time to mess around with config files. I'll close the issue, thank you very much for the help :)

**Comment by souravdas142** [comment]
@madushan1000   
> I guess adding that line to the global config in /etc or /usr/share will work too.

`wireplumber/pipewire` scan precedence like `$XDG_CONFIG_HOME/wireplumber` > `$XDG_CONFIG/wireplumber` > `$XDG_DATA_DIR/wireplumber`. So If you want to change persistently you should modify files from first two location, If you change something from `usr/share/` it will be reverted back to original as files are getting updated on new installation/upgrade.

Furthermore, you should change from one location and always make a diff between `/usr/share/[pipewire/wireplumber]` and `/etc/[pipwire/wireplumber` or `.config/[pipwire/wireplumber]` to include updated changes from package configs
