### ISSUE TITLE
Blueman notification icon in Cinnamon taskbar has disappeared

### ISSUE THREAD

**Issue by mcarans** [pipewire-debian/pipewire-debian#62]
**If you Completed all troubleshoot options, check below**     
- [X]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [X]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: [e.g. Ubuntu] Mint
 - Desktop: Environment [e.g. Gnome] Cinnamon
 - Version: [e.g. 20.04] 20.3
 - PipeWire Related packages Version: [pipewire, wireplumber, libcamera, etc.]  pipewire, wireplumber, blueman-git
 - Kernel version: 5.15.0-33.34

**Describe the bug**
I installed pipewire and blueman-git a long time ago from this PPA and it has been working well. However, after the last update, the blueman-git notification icon disappeared. I can still launch blueman-git from the Mint menu. I have tried `sudo apt remove blueman-git` followed by `sudo apt install blueman-git` but it didn't help.

**To Reproduce**
?

**Expected behavior**
Notification icon appears taskbar in bottom right corner in CInnamon

**Comment by souravdas142** [comment]
The recent change was to switch `ayatana-appindicator`. So can you confirm all components of `ayatana-appindicator` is installed ? May be you need some components of https://packages.ubuntu.com/search?keywords=ayatana&searchon=sourcenames

**Comment by mcarans** [comment]
When I do `apt list ayatana*` I get:
```
ayatana-indicator-application/focal 0.5.3-1 amd64
ayatana-indicator-common/focal,focal 0.6.3-1 all
ayatana-indicator-notifications/focal 0.4.1-1 amd64
ayatana-indicator-power/focal 2.0.94-2 amd64
ayatana-indicator-printers/focal 0.1.9-3 amd64
ayatana-indicator-session/focal 0.4.4-1 amd64
```

None of them are installed. I can install, but if `ayatana-indicator-bluetooth` from the link you gave https://packages.ubuntu.com/search?keywords=ayatana&searchon=sourcenames is needed, that would be a problem since it doesn't exist on focal (20.04LTS). Is it needed @souravdas142 ?

**Comment by souravdas142** [comment]
But as per patch https://github.com/pipewire-debian/pipewire-debian/pull/57/commits/ededc4838600d8a23586030770aa6d5ac9d98b68 It should work without `ayatana` components. I was not aware of `cinamon` by default use this. Can you give me the link for ubuntu 20.04 cinamon distro for testing ?

**Comment by mcarans** [comment]
Sure @souravdas142. It is https://linuxmint.com/edition.php?id=292

**Comment by souravdas142** [comment]
@mcarans  Thank you for reporting this. 2b288e552fd56b6260587c111bcb73b4207a5427 should fix this. Eventually pushed to the launchpad can you update to the 2.2.4-3 and check everything is working or not ?

**Comment by mcarans** [comment]
@souravdas142 That brings the icon back thanks! The only thing now is that both the icon and the application window both open on startup not just the icon. Is there any way to set it back to how it was before that only the icon launches?

EDIT: I have solved this. I had to create a startup application and launch `/usr/bin/bluetooth-applet`. `bluetooth-manager` launches both the icon and the applet.

**Comment by souravdas142** [comment]
Thank you @mcarans  for your all contributions.

closing as all issues are solved.

**Comment by ghost** [comment]
Also had this issue in Linux Mint Cinnamon 20.3 but solved it by installing the 'gir1.2-ayatanaappindicator3-0.1' apt package
