### ISSUE TITLE
blueman-applet: Missing ayatana patch - "Namespace AyatanaAppIndicator3 not available"

### ISSUE THREAD

**Issue by nexhub** [pipewire-debian/pipewire-debian#63]
Apparently there is an ayatana patch missing as described by @cschramm:
https://github.com/blueman-project/blueman/issues/1717#issuecomment-1148848013

**Desktop:**
 - Distro: Xubuntu
 - Version: 20.04.4
 - Desktop: xubuntu-desktop 2.233
 - PipeWire Related packages Version: 
`blueman-git         2.2.4-2~ubuntu20.04`
`bluez                   5.53-0ubuntu3.5`
`pipewire              0.3.51-1~ubuntu20.04`

**Describe the bug**
There is an error when starting `blueman-applet`:
`ValueError: Namespace AyatanaAppIndicator3 not available`

**To Reproduce**
Install packages from PPA and start applet.

**Expected behavior**
A working blueman applet ;)

**Workaround**
`sudo apt install gir1.2-ayatanaappindicator3-0.1`

**Log**
https://github.com/blueman-project/blueman/issues/1717#issuecomment-1128906884

**Comment by pipewire-debian** [comment]
Sorry for the mess. recently it was fixed at #62 and uploaded to the launchpad. Can you please update to the 2.2.4-3 ? Thank you.

**Comment by pipewire-debian** [comment]
from 2.2.4-3, with `AyatanaAppIndicator` and `AppIndicator` both will work, but If you want to use only AyatanaAppIndicator, install `gir1.2-ayatanaappindicator3-0.1` as It has precedence over `AppIndicator`

**Comment by pipewire-debian** [comment]
Hi @nexhub  Still have issue ? 
please suggest what should we do ? Thank you.

**Comment by nexhub** [comment]
The mentioned workaround fixes my problem. I can't provide suggestions on packaging, sorry.

**Comment by pipewire-debian** [comment]
Closing, As issue was fixed.
