### ISSUE TITLE
wishlist: Please add qpwgraph to the PPA

### ISSUE THREAD

**Issue by tormodvolden** [pipewire-debian/pipewire-debian#64]
It would be nice to have qpwgraph in the PPA. It is already in Debian unstable and the package source (https://tracker.debian.org/pkg/qpwgraph) from there builds fine on e.g. Ubuntu 20.04 with this PPA enabled.

**Comment by pipewire-debian** [comment]
Yeah sure. Will Pull it in to the PPA by this weekend.

Edit -  
> It is already in Debian unstable and the package source

https://packages.ubuntu.com/kinetic/qpwgraph it also at kinetic.

**Comment by tormodvolden** [comment]
I should note that for Ubuntu 20.04 I patched debian/control to require debhelper 12 instead of 13.

**Comment by pipewire-debian** [comment]
> for Ubuntu 20.04 I patched debian/control to require debhelper 12 instead of 13.

If you want you can use dh 13 even on ubuntu 18.04, as it was backported. So Thinking all new packages will be upgraded to use dh 13. for Old packages don't have so much time for the transition. So, probably will keep that unchanged.

**Comment by tormodvolden** [comment]
You will need to add the backported debhelper to your PPA in that case, right? And thus force the Ubuntu 20.04 users to upgrade their debhelper if they have it installed (unless they pin the original version).

**Comment by pipewire-debian** [comment]
Yes. Will it be an issue for this ? we  had been already doing this for ubuntu 18.04 see : https://launchpad.net/~pipewire-debian/+archive/ubuntu/pipewire-upstream/+build/21534705 , as per [debhelper 13 changelog](https://github.com/Debian/debhelper/blob/master/debian/changelog) should we keep default version or upgrade to 13 ? whats your suggestion ?

**Comment by tormodvolden** [comment]
Ah, I hadn't noticed the 18.04 package. You can probably go on doing the same for 20.04. I don't think it is a big issue. The newer debhelper versions should remain perfectly backwards-compatible so the users can still build their own debian packages using version 13 without problems. It becomes only an issue if you are a developer and make other packages that work with 13 and would fail on 12 (and thus on stock systems) without noticing it. The versioned debhelper dependency in those packages /should/ take care of that though. And chances are you already have enough backports or non-stock packages installed locally that you need to check your packages in a pbuilder or clean PPA anyway.

And as soon as the newer Debian packaging that you pull into the pipewire PPA actually starts to use any 13 features, patching it to work with 12 can become painful.

Maybe there could be a way to have debhelper 13 in the PPA for building, but not being pushed to users, but also this becomes inconsistent if the users want to rebuild packages themselves.

Personally I am fine with upgrading my debhelper, if it causes any trouble it is still a small price to pay for having latest PipeWire installed in wonderfully comfortable way.

**Comment by tormodvolden** [comment]
Now that I looked closer and I see that the PPA has upgraded many common packages like doxygen, x11proto-dev and libx11, any upgrade of debhelper is the least of my worries :) So please add the debhelper backport if it makes things easier.

**Comment by pipewire-debian** [comment]
There are some issue with debhelper 13, Some packages are building successfully and some are not even after changing in debian/control, so for now I think we should not upgrade it. May be we need to put it in a Todo list.

**Comment by pipewire-debian** [comment]
For `qpwgraph` see e14bc8f82996fe6f939f9899e0bd4eb2a9306ea6

**Comment by tormodvolden** [comment]
> There are some issue with debhelper 13, Some packages are building successfully and some are not even after changing in debian/control, so for now I think we should not upgrade it. May be we need to put it in a Todo list.

Is this with the official backports package https://launchpad.net/ubuntu/+source/debhelper/13.5.2ubuntu1~bpo20.04.1 ?

Are some pipewire packages not building if you upgrade debhelper?

**Comment by pipewire-debian** [comment]
> Is this with the official backports package https://launchpad.net/ubuntu/+source/debhelper/13.5.2ubuntu1~bpo20.04.1 ?      

yes.

> Are some pipewire packages not building if you upgrade debhelper?

No PipeWire packages are building fine with dh13, but some other  architecture (except amd64, arm64) of other packages have issue complaining something like it can't be installed.

**Comment by tormodvolden** [comment]
I see that in your Testing PPA, pipewire 0.3.52.r2.g9255cfb-1~ubuntu20.04 fails to build on armhf and thus blocks packages depending on it. But is it related to debhelper?

**Comment by pipewire-debian** [comment]
This is because of gcc version.

<details><summary> see snippet log below or see <a href="https://launchpadlibrarian.net/606496720/buildlog_ubuntu-focal-armhf.pipewire_0.3.52.r2.g9255cfb-1~ubuntu20.04_BUILDING.txt.gz">build_log</a> :</summary>

```bash
/tmp/cc0I3lCF.s: Assembler messages:
/tmp/cc0I3lCF.s:225: Error: selected FPU does not support instruction -- `vmul.f32 q0,q4,q8'
/tmp/cc0I3lCF.s:233: Error: selected FPU does not support instruction -- `vmul.f32 q0,q4,q8'
/tmp/cc0I3lCF.s:234: Error: selected FPU does not support instruction -- `vmul.f32 q1,q5,q9'
/tmp/cc0I3lCF.s:235: Error: selected FPU does not support instruction -- `vmul.f32 q2,q6,q10'
/tmp/cc0I3lCF.s:236: Error: selected FPU does not support instruction -- `vmul.f32 q3,q7,q11'
/tmp/cc0I3lCF.s:243: Error: selected FPU does not support instruction -- `vmla.f32 q0,q4,q8'
/tmp/cc0I3lCF.s:244: Error: selected FPU does not support instruction -- `vmla.f32 q1,q5,q9'
/tmp/cc0I3lCF.s:245: Error: selected FPU does not support instruction -- `vmla.f32 q2,q6,q10'
/tmp/cc0I3lCF.s:246: Error: selected FPU does not support instruction -- `vmla.f32 q3,q7,q11'
/tmp/cc0I3lCF.s:248: Error: selected FPU does not support instruction -- `vadd.f32 q4,q0,q1'
/tmp/cc0I3lCF.s:249: Error: selected FPU does not support instruction -- `vadd.f32 q5,q2,q3'
/tmp/cc0I3lCF.s:251: Error: selected FPU does not support instruction -- `vadd.f32 q0,q4,q5'
/tmp/cc0I3lCF.s:256: Error: selected FPU does not support instruction -- `vmla.f32 q0,q6,q10'
/tmp/cc0I3lCF.s:258: Error: selected FPU does not support instruction -- `vadd.f32 d0,d0,d1'
/tmp/cc0I3lCF.s:259: Error: selected processor does not support `vpadd.f32 d0,d0,d0' in Thumb mode
/tmp/cc0I3lCF.s:1040: Error: selected FPU does not support instruction -- `vdup.32 q10,r2'
/tmp/cc0I3lCF.s:1045: Error: selected FPU does not support instruction -- `vmul.f32 q0,q4,q8'
/tmp/cc0I3lCF.s:1046: Error: selected FPU does not support instruction -- `vmul.f32 q1,q5,q9'
/tmp/cc0I3lCF.s:1047: Error: selected FPU does not support instruction -- `vmul.f32 q2,q6,q8'
/tmp/cc0I3lCF.s:1048: Error: selected FPU does not support instruction -- `vmul.f32 q3,q7,q9'
/tmp/cc0I3lCF.s:1054: Error: selected FPU does not support instruction -- `vmla.f32 q0,q4,q8'
/tmp/cc0I3lCF.s:1055: Error: selected FPU does not support instruction -- `vmla.f32 q1,q5,q9'
/tmp/cc0I3lCF.s:1056: Error: selected FPU does not support instruction -- `vmla.f32 q2,q6,q8'
/tmp/cc0I3lCF.s:1057: Error: selected FPU does not support instruction -- `vmla.f32 q3,q7,q9'
/tmp/cc0I3lCF.s:1059: Error: selected FPU does not support instruction -- `vadd.f32 q0,q0,q1'
/tmp/cc0I3lCF.s:1060: Error: selected FPU does not support instruction -- `vadd.f32 q2,q2,q3'
/tmp/cc0I3lCF.s:1061: Error: selected FPU does not support instruction -- `vsub.f32 q2,q2,q0'
/tmp/cc0I3lCF.s:1062: Error: selected FPU does not support instruction -- `vmla.f32 q0,q2,q10'
/tmp/cc0I3lCF.s:1063: Error: selected FPU does not support instruction -- `vadd.f32 d0,d0,d1'
/tmp/cc0I3lCF.s:1064: Error: selected processor does not support `vpadd.f32 d0,d0,d0' in Thumb mode
lto-wrapper: fatal error: cc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```
</details>

I found this https://bugzilla.redhat.com/show_bug.cgi?id=1823349, So they claim it should fix in gcc-10.2.1-8 for fedora.

**Comment by pipewire-debian** [comment]
> No PipeWire packages are building fine with dh13, but some other architecture (except amd64, arm64) of other packages have issue complaining something like it can't be installed.

For example : 
https://launchpad.net/~pipewire-debian/+archive/ubuntu/testing/+packages?field.name_filter=libarchive&field.status_filter=&field.series_filter=bionic

**Comment by tormodvolden** [comment]
Have you configured your PPA to build for s390x? I don't think that is much useful.

**Comment by tormodvolden** [comment]
Anyway, the s390x package fails to build because it has `Depends: debhelper-compat (= 12)`. <s>If you upgraded debhelper there to 13, this will fail.</s> EDIT: Sorry, just noticed now this was debhelper-compat, not debhelper. I think debhelper 13 should provide the meta-package debhelper-compat (= 12) as well as (= 13).

**Comment by pipewire-debian** [comment]
I wonder then why for other architecture is not failing ? It should have backward compatibility right ?
that was an example 
Now see another one https://launchpadlibrarian.net/606563911/buildlog_ubuntu-bionic-ppc64el.cmake_3.23.2-2~ubuntu18.04_BUILDING.txt.gz, this PPA has dependency at least `testing` and log was before deleting debhelper 13.

**Comment by tormodvolden** [comment]
> I wonder then why for other architecture is not failing ? It should have backward compatibility right ? that was an example Now see another one https://launchpadlibrarian.net/606563911/buildlog_ubuntu-bionic-ppc64el.cmake_3.23.2-2~ubuntu18.04_BUILDING.txt.gz, this PPA has dependency at least `testing` and log was before deleting debhelper 13.

In this case we have `Depends: debhelper-compat (= 13)`. Are you sure debhelper 13 was available (already "published" in the PPA for this architecture) at the time of build? Not just built and uploaded?

**Comment by pipewire-debian** [comment]
> Are you sure debhelper 13 was available (already published in the PPA for this architecture) at the time of build?

yes. I clearly remember after oddly failing build I deleted.

**Comment by tormodvolden** [comment]
> I wonder then why for other architecture is not failing ? It should have backward compatibility right ?

Yes, I cannot explain this. Whether the build machine had debhelper 12 or 13 available, the dependency on debhelper-compat (= 12) should have been satisfied.

**Comment by tormodvolden** [comment]
Anyway, I recommend disabling s390x builds, which I guess nobody would be using. That is not exactly a multimedia architecture for pipewire desktop users.

**Comment by pipewire-debian** [comment]
pipewire under s390x will never be built with our configs, as libldac is enabled, and libldac will never be built under s390x again for some compilation issue. So possibly we can leave it. 

For future completeness I think we should build package which are packagable under s390x ? I remember someone mailed me for ppc64el and who knows some other person will not mail for s390x for other package (excluded pipewire) in future :sweat_smile:

**Comment by tormodvolden** [comment]
Yes, the only problem is that you may end up investing a lot of extra time supporting those 1-2 s390x/ppc64el users...

**Comment by tormodvolden** [comment]
Thanks a lot for the new PipeWire 0.3.52 packages, with qpwgraph! Upgrade went well, after restarting pipewire services and sound applications.

**Comment by tormodvolden** [comment]
BTW, I guess you can delete mini-soong from the PPA if it is not used for libldac any longer?

**Comment by pipewire-debian** [comment]
Yeah. Will delete.

**Comment by tormodvolden** [comment]
For letting pipewire build on s390x without openldac, maybe do like the Debian package  does in debian/rules:
```
ifneq (,$(filter s390x hppa m68k powerpc ppc64 sparc64,$(DEB_HOST_ARCH)))
BLUEZ5_CODEC_LDAC=disabled
else
BLUEZ5_CODEC_LDAC=enabled
endif
```
and corresponding Build-Depends:
```
				libldacbt-abr-dev [!s390x !hppa !m68k !powerpc !ppc64 !sparc64],
				libldacbt-enc-dev [!s390x !hppa !m68k !powerpc !ppc64 !sparc64],
```
In general it looks like your packaging has diverted quite a bit from what is in Debian today. Do you regularly review it?

**Comment by souravdas142** [comment]
These all were exist from the first, As I was not planed for other Archs, I kept everything simple and removed those.

If we really care for other Archs, we have to for other package also (libcamera, libldac, roc-toolkit, 
and all failed packages )

> In general it looks like your packaging has diverted quite a bit from what is in Debian today.

Yes we are packing with full features.
