### ISSUE TITLE
Add additional steps to installation instructions for Alsa configuration

### ISSUE THREAD

**Issue by 9Lukas5** [pipewire-debian/pipewire-debian#65]
I struggled a long time why my Java applications sound won't work until I discovered, just out of luck, that my configuration faults are located in the Alsa configurations.

Under `/etc/alsa/conf.d` my system has a bunch of files, whereas the only tested distribution coming with pipewire working  out of the box has just the two pipewire files in them.

I did the following:
- Alsa: removed everything from `/etc/alsa/conf.d`
- Jack: removed everything from `/etc/ld.so.conf.d`
- installed `pipewire-audio-client-libraries`
- copied Alsa configuration from the pipewire docs:
    ```sh
    sudo cp /usr/share/doc/pipewire/examples/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/
    ```
- copied Jack configuration from the pipewire docs:
    ```sh
    sudo cp /usr/share/doc/pipewire/examples/ld.so.conf.d/pipewire-jack-*.conf /etc/ld.so.conf.d/
    sudo ldconfig
    ```

This fixed my Java applications which use Alsa. Before this it seems some old/distro default configs in there interfered with pipewire. 

Could that information be added to the section 3.B of the Readme?

**Comment by pipewire-debian** [comment]
Sorry for late reply.
Yeah sure. I will add it. Thank you.

**Comment by 9Lukas5** [comment]
If you didn't do it already: I tested a bit more and it seems the conflicting file in my case was `/etc/alsa/conf.d/99-pulse.conf`. Deleting this file was already enough to get it working.

oh an btw: don't worry,didn't expect to get a response like immediately :grinning:

**Comment by souravdas142** [comment]
shouldn't it go under trouble shooting page ? I will add it to there.

**Comment by souravdas142** [comment]
see https://github.com/pipewire-debian/pipewire-debian/wiki/Troubleshooting#if-some-java-application-cant-produce-sound-you-might-need-to-below-fix . Thank you.
