### ISSUE TITLE
Distorted mic audio with bluetooth

### ISSUE THREAD

**Issue by hadim** [pipewire-debian/pipewire-debian#69]
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: ubuntu 22.04
 - Desktop: Environment: Gnome
 - Version: 22.04
 - PipeWire Related packages Version: latest as of today 0.3.53
 - Kernel version: `5.15.0-40-generic`

**Describe the bug**

I am hitting this upstream bug: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2492. I guess this fix will come in the next version 0.3.54 but in the meantime downgrading to 0.3.52 seems to be the only way to fix it.

I tried to downgrade pipewire with synaptic but the 0.3.52 version is not proposed. Do you know how it's possible to downgrade easily without downloading all the deb files individually? If no, do you have a list of exact dev files to download and install from the PPA?

Thanks

**Comment by souravdas142** [comment]
Sorry, I am not aware of any method apart from manual downloading all packages and installing them. You if you look into some other distros, also they don't offer any method which can manage by the same package manager.

However I made a script which can only may help you to download packages. Rest of thing you need to make your own.

<details><summary> Please see:</summary>

```bash
#!/bin/bash

PPA=testing
BUILDNUM=24126721
ARCH=amd64
VER=0.3.53
REL=1
DIST=ubuntu20.04
TYPE=deb


# you can comment out if some package is not needed
packages=(
 libpipewire-0.3-0
 libpipewire-0.3-dev
 libpipewire-0.3-modules
 libpipewire-module-x11-bell
 libspa-0.2-dev
 libspa-0.2-modules
 pipewire-doc
 pipewire-locales
 pipewire
 pipewire-bin
 pipewire-pulse
 pipewire-audio-client-libraries
 pipewire-tests
 gstreamer1.0-pipewire
 libspa-0.2-bluetooth
# libspa-0.2-libcamera
 libspa-0.2-jack
)



for pkgname in ${packages[@]};
do
	URL="https://launchpad.net/~pipewire-debian/+archive/ubuntu/${PPA}/+build/${BUILDNUM}/+files/${pkgname}_${VER}-${REL}~${DIST}_${ARCH}.${TYPE}"
	echo -e "\nDownloading ${pkgname}...\nfrom ${URL}\n"
	curl -LJO ${URL}
done

echo -e "\nDownload has been finsished, please follow bellow recomendation\n"

echo -e "\nNext step is, remove all pipewire packages (ppa-purge program you need),\nReinstall all packages with 'sudo dpkg -i *.deb'"

```

</details>

**Comment by souravdas142** [comment]
However I will release (may be from master or cherry-picked from master) another version soon, which mitigate all bugs, may be you also notice channel mixing problem([#2490](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2490)), (right channel have no sound) after when another MR ([#1305](https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1305)) merge will happen.

**Comment by hadim** [comment]
Thanks for the update. I'll either use your script or wait for your release.

**Comment by souravdas142** [comment]
A downgrade would be worth for now If you have major issue with distorted mic (I can't give any commitment for the next release date.) else wait for next downstream release.

**Comment by ashleysommer** [comment]
Just commenting here to say I'm too affected by https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2492, so I will watch this thread and upgrade as soon as a hotfix is released (after the upstream MR is merged).

**Comment by KhanhVanCong** [comment]
@souravdas142 Could you give me a favor on how I can downgrade to 0.3.52? I tried your script and changed the variable version to 0.3.52 but it's not working. Thank you.

**Comment by souravdas142** [comment]
Sorry guys, `curl` may be not right fit at here. please ignore https://github.com/pipewire-debian/pipewire-debian/issues/69#issuecomment-1174037568

please use below script:


```bash
#!/bin/sh

PPA=testing
ARCH_BUILDNUM=24096784
TYPE="*.deb"

# ARCH_BUILDNUM = will different for each build and architecutre
# goto : https://launchpad.net/~pipewire-debian/+archive/ubuntu/testing/+packages
# select a package, select an architecture, copy the BUILDNUM (i.e. all number of last part of the url)
# for example : https://launchpad.net/~pipewire-debian/+archive/ubuntu/testing/+build/23808323,
# BUILDNUM = 23808323, this will be different for every architecture and every distribution name, So gave name 
# ARCH_BUILDNUM

wget -r -l1 -nd -np -A ${TYPE} https://launchpad.net/~pipewire-debian/+archive/ubuntu/${PPA}/+build/${ARCH_BUILDNUM}/

echo -e "\nDownload has been finsished, please follow bellow recomendation\n"

echo -e "\nNext step is, remove all pipewire packages (ppa-purge program you need),\nReinstall all packages with 'sudo dpkg -i *.deb'"
```

**Comment by KhanhVanCong** [comment]
@souravdas142 It's working now. Thank you so much :)

**Comment by the-nic** [comment]
The fixes seem to have landed on pipewire master now

**Comment by souravdas142** [comment]
As issue is fixed now, Closing it, can be opened if something wrong happened.

**Comment by hadim** [comment]
I confirm the fix by simply upgrading the packages on the PPA. Thanks!
