### ISSUE TITLE
💥support for ubuntu 18.04 AND MX Linux is added💥

### ISSUE THREAD

**Issue by pipewire-debian** [pipewire-debian/pipewire-debian#7]
> ## :fire: For 18.04, need a lot of changes, And there is lot of dependencies to be resolved first.
> 
>  I actually fork PW debian source from debian experimental, it was made for PW 0.3.24. [Original Source](https://salsa.debian.org/utopia-team/pipewire/-/tree/debian/0.3.24-1)
> 
> 
> **If anyone  interested and want to contribute, Give a PR by Forking this repo.**
> 
> **Instructions**
> 
> 1. Create a separate  branch rebase on  development branch
> 2. make a dir `ubuntu18` on branch root and Copy the existing `pipewire/debian` to `ubuntu18`
> 3. make compatible `ubuntu18` to build  PW successfully  locally by resolving related dependencies.
> 4. make compatible  related dependencies to make other dependencies
> 5. place  all sources with `debian/`  of each source package that are need to be build from locally to `ubuntu18/`
> 6. Test each packages carefully
> 7. make a documentaion how dependencies are related to each other.
> 
> and finally
> 
> 8. Give a PR, I will be checked and merged.
> 
> :warning:  **Do not import lot of packages from other version of ubutnu**
> **So, move a minimalist approach in case of importing. Import a package that MUST NEED TO BE IMPORTED**
> 
> :information_source:  **All documentaion related to building PipeWire package is available on  [wiki](https://github.com/pipewire-debian/pipewire-debian/wiki)**
> 
# :fire: :fire: Support for Ubuntu 18.04 is added 1de81152f0ade27beefc1fbfbe66aaeb48fb469e
* **Support for ubuntu 18.04 is added**
  * The problem was with systemd version.
  * ubuntu 18.04 has systemd 237 but our PW services supports
    version >=239, No way to upgrade systemd
  * To resolve this issue a patch
    `Fix_incompatible_PW_Service_1804.patch` is added
  * All test is passed.
  * Checkout Launchpad PPA to install.

**Comment by souravdas142** [comment]
No need to show under issue more
