### ISSUE TITLE
Consider not printing changelog in `postinst` script

### ISSUE THREAD

**Issue by BHSPitMonkey** [pipewire-debian/pipewire-debian#70]
Since the 0.4.1 release (391b156), the Debian post-install script for wireplumber has been printing the newest version's changelog to standard output during every installation/update (here: https://github.com/pipewire-debian/pipewire-debian/blob/development/wireplumber/debian/wireplumber.postinst).

It's not a great practice, in my opinion, for packages to display large amounts of informational text like this in the course of installing routine `apt` updates. There is a more standard, opt-in way of implementing this functionality using [apt-listchanges](https://manpages.debian.org/testing/apt-listchanges/apt-listchanges.1.en.html) which package maintainers can provide support for by including a NEWS.Debian or changelog file with the relevant entries. This has the added benefit of being able to show changes spanning multiple updates (e.g. if the user is upgrading from version N to N+2).

**Comment by souravdas142** [comment]
Thank you. I did this because if there is some packing issue, user shouldn't go to the upstream and create an issue there instead let them know to open at this repo. And user should check some changelog before creating issue (i.e. package splitting or any packaging related changes). Also give them url for the full changelog. But now I realise a large amounts of informational text should be avoid.

> There is a more standard, opt-in way of implementing this functionality using [apt-listchanges](https://manpages.debian.org/testing/apt-listchanges/apt-listchanges.1.en.html) which package maintainers can provide support for by including a NEWS.Debian or changelog file with the relevant entries. This has the added benefit of being able to show changes spanning multiple updates (e.g. if the user is upgrading from version N to N+2).

I am really not aware of it. Thats a great suggestion. Will try to implement this. But must match the above thing also. Currently I am busy with another thing. I will surely check it later. Thank you.

**Comment by souravdas142** [comment]
It is the best approach no doubt. However some noobs even they don't read the installation guides properly still now. They might end up with opening issue on upstream with noobs question and make noise there. It had been occurred many times in the past.
And `apt-listchangelogs` need to be installed first along with some configs should be made before it is usable (for ref: http://jxf.me/entries/better-apt-ubuntu/)

Also some blogs write their tutorial their own way which might be wrong (also seen the past).

**So Its necessary to show users forcefully some text related to, where they need to heads up for issue tracking, tutorial and some other important information. However from now, I will  minimize the verbosity of texts, from now It will be shown only debian packaging related information, some important information, and link for the upstream changelogs**

> This has the added benefit of being able to show changes spanning multiple updates (e.g. if the user is upgrading from version N to N+2).

**To handle this situation, also a link will be given redirects to debian/changelog, they can manually read the changelogs from N to N+k**

**Everything will be as much as shortest possible I can, to show the text will try to achive withing 5 to 6 lines**. 

Hope you will understand this. Thank you.

**Comment by souravdas142** [comment]
I tried to not printing changelogs on terminal while installing. But I think still some little bit information might have to show on screen. So only those things are now printing.

Closing as completed.
