### ISSUE TITLE
Cannot load repo / install libfdk-aac2 (novice)

### ISSUE THREAD

**Issue by gregvp00** [pipewire-debian/pipewire-debian#72]
**Desktop (please complete the following information):**
 - Distro: Debian 11 (bullseye)
 - Desktop: Gnome
 - Version: 3.38.5
 - PipeWire Related packages Version: pipewire 0.3.19 
 - Kernel version: 5.10.0-16-amd64 

**Describe the bug**
I tried to follow the readme on this github but in 2º step, **libfdk-aac2** is not found, then i tried to install **libfdk-aac1** with `sudo apt install` and It shows the same thing.

I get to solve **libfdk-aac1** with `sudo dpkg -i libfdk-aac1_0.1.6-1_amd64.deb`. But **libfdk-aac2** stills not being found, I could install it with dpkg, but the problem is that I just check `sudo apt update` and this appears:
```
greg00@D0-50-99-4C-1E-64:~$ sudo apt update
Obj:1 http://security.debian.org/debian-security bullseye-security InRelease
Obj:2 http://ftp.es.debian.org/debian bullseye InRelease                      
Ign:3 http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu kinetic InRelease
Obj:4 http://ftp.es.debian.org/debian bullseye-updates InRelease
Ign:5 http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu bullseye InRelease
Err:6 http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu kinetic Release
  404  Not Found [IP: 185.125.190.52 80]
Err:7 http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu bullseye Release
  404  Not Found [IP: 185.125.190.52 80]
Leyendo lista de paquetes... Hecho
E: El repositorio «http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu kinetic Release» no tiene un fichero de Publicación.
N: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
N: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
E: El repositorio «http://ppa.launchpad.net/pipewire-debian/pipewire-upstream/ubuntu bullseye Release» no tiene un fichero de Publicación.
N: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
N: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
```
_The error is in spanish._
At first I check if the DNS wasn't working, but I can ping without problems.

**To Reproduce**
1-Manually adding the Launchpad PPA (Alternative).
2-Trying to install the dependencies libfdk-aac2 and libfdk-aac1.
3-Solving libfdk-aac1 with `sudo dpkg -i libfdk-aac1_0.1.6-1_amd64.deb`.

**Comment by souravdas142** [comment]
remove what you have installed with `dpkg -i`. Everything will be a smooth install with `apt-get`


can you edit `/etc/apt/source.list.d/pipewire-upstream.list` and change `bullseye/kinetic` to `focal` ? and filename may differ it depends on you whatever you had name it

**Comment by souravdas142** [comment]
please blindly follow the  installation log if you are unable to install by your own : https://pastebin.com/3vtCQt7T

you can see how smooth everything gone right ? no need of any `dpkg -i` install.


If you see some errors, you can search on google because it tends to more generic problem can be found on google easily.

If there are problems only for pipewire/wireplumber packages you can report it here.

**Comment by gregvp00** [comment]
> 

Yes, I change **bullseye** to **focal** and `sudo apt update` stills with the same error.

--------

This is the 10º time I try to install/update Pipewire, I have reinstalled Debian 6 times and lost 2 days of my life. I don't know if It's something to do with the OS version, but I will close this thread because I lost my sanity.

**Comment by souravdas142** [comment]
> I don't know if It's something to do with the OS version

No, Nothing about OS version. Thank you.
