### ISSUE TITLE
Few critical bluetooth regressions were fixed in 0.3.54

### ISSUE THREAD

**Issue by ofirnk** [pipewire-debian/pipewire-debian#73]
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: Ubuntu
 - Desktop: Environment Gnome]
 - Version: 22.04
 - PipeWire Related packages Version: wireplumber
 - Kernel version: 

**Describe the bug**

There are few critical bluetooth (mainly buffer) related bugs That were inntroduced in 0.3.53

1. Would you be able to release 0.3.54 soon, as it fixes those regressions? 
2. How would you recommend working around the regressions? Is a revert plausible? How would you recommend applying it locally, without loosing future updates? 

And an opportunity to thank you for all the work in bringing pipewire to Debian based distros, that's a great addition!

**Comment by souravdas142** [comment]
> Would you be able to release 0.3.54 soon, as it fixes those regressions?

Yes I am aware of it. But was busy from couple of day on other thing. will release today.

for 2) please wait

**Comment by souravdas142** [comment]
Hope everything is ok. To let you know, **If some release is made by upstream, I will release the nearest weekend of the release day**. Thank you.
