### ISSUE TITLE
0.3.56 (released 2 day ago) - how long is the typical wait for PPA pkgs to come out?

### ISSUE THREAD

**Issue by dreamcat4** [pipewire-debian/pipewire-debian#74]
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: `Ubuntu`
 - Version: `22.04`
 - PipeWire Related packages Version: `pipewire 0.3.55`

**Describe the bug**

The PPA currently is serving pipewire `0.3.55`. Which has some issues (bugs) so I would like to upgrade. However while there is `0.3.56` release (2 days ago). The PPA isn't updated yet. So I just wanted to check and make sure that this is normal delays. That isn't some issue with the builds system. For example - there is no builds being logged on launchpad build farm yet.

So do you have to manually push a git for launchpad with a new git SHA has every time?

**To Reproduce**

Wait some days. Checking the PPA.

**Expected behavior**

At some point... new pkgs will arrive! And I will be very happy when that does occur. :)

**Additonal Information (If applicable):**                                          

Thanks for maintaining these builds system. Is complicated mguffins I know ;)

**Comment by dreamcat4** [comment]
reason for my request:

Pipewire is crashing too much / too often. Release notes for next version says:

> # PipeWire 0.3.56 (2022-07-19)
> * A critical bug that could crash JACK apps was fixed.
> * Many more bugfixes and improvements.

**Comment by dreamcat4** [comment]
hello.
have been informed that you have a policy of pulling from upstream once every 15 days... so presumably that means the next build will be in 5 more days

**Comment by souravdas142** [comment]
try after sometime, 0.3.56 has some issue with compilation, that's why I didn't release to main repo. It was already there at testing repo. released now. for ubuntu 18.04 I need to consult with upstream for the same compilation failed.

> ... pulling from upstream once every 15 days.

Yes, but if its quick release I have some difficulties to manage time to release some time.

**Comment by dreamcat4** [comment]
thanks for looking into those build issue. very much appreciated

**Comment by dreamcat4** [comment]
it worked, have now updated to 0.3.56
