### ISSUE TITLE
Instructions how to build .debs locally?

### ISSUE THREAD

**Issue by dreamcat4** [pipewire-debian/pipewire-debian#78]
Hello,
Am able to follow the official upstream instructions and....

* Can compile pipewire from git repo
* Want to generate `.deb` pkgs
* Cannot generate my own `.deb` pkgs

It seems, when I look for such guide none exists! Can you help?

The main reason I want to do this is to avoid installing pipewire directly (outside of apt / dpkg). And not to leave un-tracked files / mess up my host system. However... still I need to install arbitary git commit(s). Not just the tagged released. 

* This then allow me to do git bisect on some bug / bugs of pipewire.
* I look in your repo, and can see some scripts are downloading release tarballs

Ideally, if you can please help me understand how to get from the pipewire git builds --> to this repo. And then generate the .deb files?

For example, I try moving the `debian` folder --> into the pipewire git. Then running:

```sh
dpkg-deb --build .
```

and it complains with an error message:

```sh
[id:~/.builds/audio/firewire/pipewire] tag: 0.3.58+* 2 ± dpkg-deb --build .
dpkg-deb: error: parsing file './DEBIAN/control' near line 58:
 missing 'Package' field
```

So... is it necessary to use some OpenSUSE / OBS build toolchain? (rather than the standard debian tooling?)

If you can please help this matter. And give some aid. Would really appreciate it very much... as cannot find anybody else to help. Many thanks.

**Comment by souravdas142** [comment]
its easy.. get the src from git
cd into src
to get version run `git describe --tags --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'`

make a tarball from src $PKGNAME_$VERSION.orig.tar.gz outside src move debian/ into src dir

and follow https://github.com/pipewire-debian/pipewire-debian/wiki

**Comment by souravdas142** [comment]
The wiki was written in its initial day, so may have discrete information but will help you a lot., you can also contribute to the wiki if you find something.

**Comment by dreamcat4** [comment]
ok so...
unfortunately did not properly understand this step:

> make a tarball $PKGNAME_$VERSION.orig.tar.gz outside src move debian/ into src dir

or what to do after that step!

any concrete example maybe can you give there? it would really help thanks

**Comment by souravdas142** [comment]
> any concrete example maybe can you give there?

This whole repo is an example, you can read above wiki, The dir structure give you an Idea.

**Comment by dreamcat4** [comment]
ah ok, have now finally found the page you were referring to, "Describing Project Tree"...

https://github.com/pipewire-debian/pipewire-debian/wiki/Describing-Project-Tree

Which has those missing steps. Thank you was what I had been missing there.
