### ISSUE TITLE
Provide -dbgsym packages

### ISSUE THREAD

**Issue by the-nic** [pipewire-debian/pipewire-debian#80]
This is not a bug report, but rather a feature request for the ppa packages.

So I've recently observed a crash in `pipewire-pulse` and even have a coredump of the process. In order to report a bug upstream, I'd like to provide the stack trace to help fixing the bug. However, the ppa-repository is currently missing the `-dbgsym` variants of the packages.

Would it be possible to provide them, too?

**Comment by souravdas142** [comment]
https://launchpad.net/~pipewire-debian/+archive/ubuntu/pipewire-upstream/+packages?field.name_filter=pipewire&field.status_filter=published&field.series_filter=jammy

install `*.ddeb` files.

If it solves the problem please close it.

**Comment by the-nic** [comment]
So there is no way to use the package manager for that? It sounds a bit inconvenient, especially if the package is updated, isnt it?

**Comment by souravdas142** [comment]
see : https://askubuntu.com/questions/487222/how-to-install-debug-symbols-for-installed-packages

**Comment by the-nic** [comment]
But ddebs.ubuntu.com does only contain outdated `pipewire-bin-dbgsym` packages - its active on my system. The ones from this repo are not available via apt.

**Comment by souravdas142** [comment]
Yes probably need to download manually and give "sudo dpkg -i *.ddeb". Or even search on google, this is more generic not related to pipewire.

Thank you.

**Comment by the-nic** [comment]
The debug packages contain the debug symbols for the binaries compiled. Thus they have to be created together with the binary packages. It just doesnt make sense that anyone else could provide them.

**Comment by souravdas142** [comment]
*.ddeb are provided with binaries see above link. What I am telling probably you have to download them from launchpad from the same PPA. Or google it how to make it possible your package manager install them like normal package installation when you want with some extra options or args.

Yes I know it doesn't make sense if someone provide *ddeb package as they have symbol files for debugging purpose with gdb or needed to generate backtraces. So please go ahead with download them manually and install them from the same PPA. Or search on google how to make possible your package manager install them from the same PPA. 

Thank you.

**Comment by the-nic** [comment]
Okay, the trick was to add `main/debug` to the sources.list file, see also https://wiki.ubuntu.com/DebuggingProgramCrash#Installing_dbgsym_packages_from_a_PPA
