### ISSUE TITLE
Is there auto build & packaging script for all ppa's files?

### ISSUE THREAD

**Issue by olosegres** [pipewire-debian/pipewire-debian#83]
I want to build & package all ppa's files myself.
Is there auto build & packaging script for all ppa's files (pipeline configuration), or some instructions?

**Comment by souravdas142** [comment]
No need to generate packages for old builds head to https://launchpad.net/~pipewire-debian/+archive/ubuntu/pipewire-upstream/+packages?field.name_filter=pipewire&field.status_filter=&field.series_filter=focal  download *.deb packages in a directory install them with `dpkg -i *.deb`

**Comment by user3354** [comment]
Such a script would be helpful to build newer versions of pipewire. This PPA is very helpful, thanks a lot.

**Comment by souravdas142** [comment]
Closing as Completed
