### ISSUE TITLE
Bug: Libraries are downloaded to different locations, which means that packages don't work as expected

### ISSUE THREAD

**Issue by NunoSempere** [pipewire-debian/pipewire-debian#84]
**Desktop (please complete the following information):**
 - Distro: Ubuntu
 - Desktop: Environment GNOME
 - Version: 20.04
 - PipeWire Related packages Version: [pipewire, wireplumber, libcamera, etc.] 
 - Kernel version: 

**Describe the bug**

Packages related to , like libspa-0.2-bluetooth or , are downloaded to `/usr/lib/x86_64-linux-gnu/spa-0.2`. But pipewire expects them to be in `/usr/local/lib/x86_64-linux-gnu/spa-0.2`. 

This leads to errors such as:

```
M 21:25:11.582983          wp-device ../lib/wp/device.c:619:wp_spa_device_new_from_spa_factory: SPA handle 'api.bluez5.enum.dbus' could not be loaded; is it installed?
M 21:25:11.582999       script/bluez bluez.lua:167:createMonitor: PipeWire's BlueZ SPA missing or broken. Bluetooth not supported.
```

which I just spent way too much time debugging.

**To Reproduce**
- Install 

**Expected behavior**
I expected bluetooth to work right after downloading libspa-0.2-bluetooth, rather than have to move it from `/usr/lib/x86_64-linux-gnu/spa-0.2` to `/usr/local/lib/x86_64-linux-gnu/spa-0.2`. 

**Screenshots**
![pipewire-1](https://user-images.githubusercontent.com/16527456/208318580-bdce4186-08bb-4402-a03d-c6083eace005.png)

![pipewire-2](https://user-images.githubusercontent.com/16527456/208318573-b69f12cb-e7ec-48e9-9b12-dd3d3d4ab256.png)

**Journal log and status of related services**

**Proposed solution**

Either coordinate libraries to use the same directory, or check on more than one directory.

**Comment by souravdas142** [comment]
pw and wp both is being built with `PREFIX=/usr` for this PPA. You might be installing half packages from some other PPA  (which configs `PREFIX=/usr/lib`) and some packages from this one, Somewhere you definitely mixed packages from multiple PPA, thats why the conflict came. Please remove all pipewire & related packages and reinstall them from one repo.

Here I locally tested with pw 0.3.63 and wp 0.4.13, there is no such error seen.

**Comment by NunoSempere** [comment]
> Here I locally tested with pw 0.3.63 and wp 0.4.13, there is no such error seen.

My versions were:

```
$ pipewire --version
pipewire
Compiled with libpipewire 0.3.47
Linked with libpipewire 0.3.47
$ wireplumber --version
wireplumber
Compiled with libwireplumber 0.4.11
Linked with libwireplumber 0.4.11
```

Yes, this might have been it/that's probably it. Also for <https://github.com/pipewire-debian/pipewire-debian/issues/85>.

Any thoughts on what could be done so that this doesn't happen to other users?

**Comment by souravdas142** [comment]
This is before installing something from one PPA just check, whether there is other same package installed, and try to remove them if possible or try to downgrade to default package version.

Closing as Completed.
