### ISSUE TITLE
Can't install pipewire-audio-client-libraries

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [pipewire-debian/pipewire-debian#86]
**If you Completed all troubleshoot options, check below**     
- [*]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [*]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: [Ubuntu]
 - Desktop: Environment [Gnome]
 - Version: [22.10]
 - PipeWire Related packages Version: [pipewire-0.3.62-1~22.04.sav0] 
 - Kernel version: 5.19.0-26

**Describe the bug**
Then run the: `sudo apt install pipewire-audio-client-libraries`
It gives me this error:
`The following packages have unmet dependencies.
 pipewire-alsa : Depends: pipewire (= 0.3.60.r2.g518ccdf-7~ubuntu22.10) but 0.3.62-1~22.04.sav0 is to be installed
                 Depends: libpipewire-0.3-0 (= 0.3.60.r2.g518ccdf-7~ubuntu22.10) but 0.3.62-1~22.04.sav0 is to be installed
 pipewire-jack : Depends: pipewire (= 0.3.60.r2.g518ccdf-7~ubuntu22.10) but 0.3.62-1~22.04.sav0 is to be installed
                 Depends: libpipewire-0.3-0 (= 0.3.60.r2.g518ccdf-7~ubuntu22.10) but 0.3.62-1~22.04.sav0 is to be installed
E: Unable to correct problems, you have held broken packages.`

**To Reproduce**
Install the ubuntu 22.10 and add pipewire-debian ppa after these upgrade all packages,reboot,and try to install pipewire-audio-client-libraries package

**Expected behavior**
Just ran the command: `sudo apt install pipewire-audio-client-libraries` 

**Screenshots**
https://www.mediafire.com/view/qfrmfebspat3ixz/Screenshot_from_2022-12-21_13-46-05.png/file

**Journal log and status of related services**
error: 
`The following packages have unmet dependencies.
 pipewire-alsa : Depends: pipewire (= 0.3.60.r2.g518ccdf-7~ubuntu22.10) but 0.3.62-1~22.04.sav0 is to be installed
                 Depends: libpipewire-0.3-0 (= 0.3.60.r2.g518ccdf-7~ubuntu22.10) but 0.3.62-1~22.04.sav0 is to be installed
 pipewire-jack : Depends: pipewire (= 0.3.60.r2.g518ccdf-7~ubuntu22.10) but 0.3.62-1~22.04.sav0 is to be installed
                 Depends: libpipewire-0.3-0 (= 0.3.60.r2.g518ccdf-7~ubuntu22.10) but 0.3.62-1~22.04.sav0 is to be installed
E: Unable to correct problems, you have held broken packages.`
status of pipewire: 
● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; preset: enabled)
     Active: active (running) since Wed 2022-12-21 13:35:19 MSK; 12min ago
TriggeredBy: ● pipewire.socket
   Main PID: 2207 (pipewire)
      Tasks: 2 (limit: 18846)
     Memory: 13.7M
        CPU: 9.625s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─2207 /usr/bin/pipewire

Dec 21 13:35:19 deus-pc systemd[2199]: Started PipeWire Multimedia Service.
Dec 21 13:35:19 deus-pc pipewire[2207]: mod.rt: Can't find xdg-portal: (null)
Dec 21 13:35:19 deus-pc pipewire[2207]: mod.rt: found session bus but no portal
Dec 21 13:35:19 deus-pc pipewire[2207]: mod.x11-bell: XOpenDisplay() failed

**Comment by souravdas142** [comment]
The package you installed from different ppa. you need to completely remove that ppa along with all packages before installing from this one.

**Comment by Bogdan-Torkhov** [comment]
Helped,thanks :)
