### ISSUE TITLE
Question: does this work with Linux Mint 20.1 and are the setup steps the same?

### ISSUE THREAD

**Issue by mcarans** [pipewire-debian/pipewire-debian#9]
Thanks for your efforts to make this PPA. I am interested in installing this PPA on Linux Mint 20.1 and want to check that it will work with that distro. Are you able to confirm that the setup steps are the same or say what needs to be done to make it work?

**Comment by souravdas142** [comment]
Linux mint is Ubuntu based. So yes... the setup steps are the same. Sorry for the confusion In readme section. you should follow  [this](https://github.com/pipewire-debian/pipewire-debian/blob/master/README.md#1-ppa-configuration) for the 1st step "PPA CONFIGURATION" rest steps are same.

extra tips : you may also install `blueman-git` (git version of blueman) to get the full benefits of pipewire.

**Comment by pipewire-debian** [comment]
as th OP got his ans. I am closing it now.
