### ISSUE TITLE
Plz Update to Lunar

### ISSUE THREAD

**Issue by CosmicFusion** [pipewire-debian/pipewire-debian#90]
I need this PPA because it has BT AAC audio, but it's on kinetic and older only rn

**Comment by zomp** [comment]
(Kinetic packages work to me on Lunar. I have them installed prior to distro upgrade, but installing them to Lunar might also work.)

**Comment by KhensU** [comment]
Kinetic packages work for now. But without a separate Lunar build there might be conflicts in the future.

**Comment by souravdas142** [comment]
Hi @CosmicFusion ,

Enabled for Lunar. Please upgrade and feel free if there is any issue while upgrading.

**Comment by CosmicFusion** [comment]
Tysm
