### ISSUE TITLE
Strange packages on the repos

### ISSUE THREAD

**Issue by mhalano** [pipewire-debian/pipewire-debian#92]
Some strange packages are present in both repositories (pipewire and wireplumber). Can be a security breach? I found the package `ppa-purge` that has no reason to be in this repository. https://ppa.launchpadcontent.net/pipewire-debian/pipewire-upstream/ubuntu/pool/main/p/ppa-purge/

**Comment by souravdas142** [comment]
This is not a strange package  but a helper to remove the ppa along with any packages belongs to it and made downgrade them to system default.

the package is already available on official ubuntu. this is the same version. This package is here because of other debian based distros doesn't have this package. so they can use it to downgrade them.

**Comment by mhalano** [comment]
Yeah, but it's out of the scope of the repository and this package version is bigger than mine on Ubuntu 23.04, so this package tried to install itself on my system.

**Comment by souravdas142** [comment]
This package is here because if some one facing issue so they can quickly downgrade them where the package is not available.

If a repo says how to install something, it has also responsible for telling how to uninstall or downgrade them. So I don't think its out of scope here. 

Thank you.

**Comment by mhalano** [comment]
I understand your point, but ppa-purge is already available in Ubuntu repositories, and imagine if every PPA available did the same.

**Comment by souravdas142** [comment]
This ppa doesn't made not only for Ubuntu... if you see README.MD, its for all debian based distros, where ppa purge is not available, by making ppa purge available to those distros enabling them to keep same intention.
