### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'people' when using add-apt-repository command

### ISSUE THREAD

**Issue by SJTheGreat06** [pipewire-debian/pipewire-debian#93]
**If you Completed all troubleshoot options, check below**     
- [🗸 ]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [🗸]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: Debian
 - Desktop Environment: XFCE
 - Version: 12 (Bookworm)
 - PipeWire Related packages Version: PPA
 - Kernel version: 6.1.0-10-amd64

**Describe the bug**
When executing the `add-apt-repository` command with the following repository: `ppa:pipewire-debian/pipewire-upstream`, an `AttributeError` occurs, stating that a 'NoneType' object has no attribute 'people'. This error prevents the command from successfully retrieving information from Launchpad (LP).

**To Reproduce**
Steps to reproduce the behavior: Execute the command: `sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream`

**Expected behavior**
The specified PPA should be added successfully without any errors.

**Screenshots**
![image](https://i.imgur.com/F0G92Sm.png)

**Comment by souravdas142** [comment]
for debian, manually add repo to /etc/sources.list.d/
