### ISSUE TITLE
Is an update planned for version 0.3.74?

### ISSUE THREAD

**Issue by user3354** [pipewire-debian/pipewire-debian#94]
Hi,

I know you are very busy. Is there any way to support an update to 0.3.74? There were a lot of updates and bugfixes in the last weeks. Thanks again for this PPA.

**Comment by dreamcat4** [comment]
As it's been said before, he is busy and will (most likely) eventually get around to update in due course. For not to hurry / disrupt. This is indeed... how we have our pkging setup for these distros. And it's gets provided to a high quality standards of as a result.

**Comment by souravdas142** [comment]
Hi Updated to 0.3.76. please check.

**Comment by user3354** [comment]
At the moment I can only confirm that it works with Linux Mint 21.2. Thanks a lot for your effort.

**Comment by souravdas142** [comment]
As complited
