### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by rw-bowman** [pipewire-debian/pipewire-debian#95]
Thank you so much for your time in offering pipewire this way. I was wondering if an update to the latest version is comming soon. pw-jack is broken in the 3.78 version which I have, and would like the fix offered in 3.79.

**Comment by souravdas142** [comment]
Hi,

Done. Please check.

**Comment by rw-bowman** [comment]
Working great thank you!

**Comment by souravdas142** [comment]
As fixed.
