### ISSUE TITLE
describe the issue title in short and meaningful

### ISSUE THREAD

**Issue by AhmedSalim2** [pipewire-debian/pipewire-debian#96]
**If you Completed all troubleshoot options, check below**     
- [ ]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [ ]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Desktop (please complete the following information):**
 - Distro: [e.g. Ubuntu]
 - Desktop: Environment [e.g. Gnome]
 - Version: [e.g. 20.04]
 - PipeWire Related packages Version: [pipewire, wireplumber, libcamera, etc.] 
 - Kernel version: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
(snapshot of PW related services or anything)

**Journal log and status of related services**

**Additonal Information (If applicable):**                                          
.                                          
.                                          
.

**Comment by souravdas142** [comment]
??
